Repository viridIT/vSMTP, pull requests merged in 2022-12, with the labels that each got.

#793 Staging the next candidate (rc3)
  .github/workflows/pre-release.yaml
  .github/workflows/staging.yaml
  Cargo.lock
  examples/antivirus/vsmtp.vsl
  examples/config/auth.vsl
  examples/config/complete.vsl
  examples/config/logging.vsl
  examples/config/minimal.vsl
  examples/config/secured.vsl
  examples/config/simple.vsl
  examples/config/tls.vsl
  src/vqueue/Cargo.toml
  src/vsmtp/plugins/vsmtp-plugin-vsl/Cargo.toml
  src/vsmtp/vsmtp-auth/Cargo.toml
  src/vsmtp/vsmtp-common/Cargo.toml
  src/vsmtp/vsmtp-config/Cargo.toml
  src/vsmtp/vsmtp-core/Cargo.toml
  src/vsmtp/vsmtp-delivery/Cargo.toml
  src/vsmtp/vsmtp-docs/Cargo.toml
  src/vsmtp/vsmtp-mail-parser/Cargo.toml
  src/vsmtp/vsmtp-protocol/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/Cargo.toml
  src/vsmtp/vsmtp-server/Cargo.toml
  src/vsmtp/vsmtp-test/Cargo.toml
Labels: B-candidate

#795 Release v1.4.0-rc.3
  .github/workflows/pre-release.yaml
  .github/workflows/staging.yaml
  Cargo.lock
  examples/antivirus/vsmtp.vsl
  examples/config/auth.vsl
  examples/config/complete.vsl
  examples/config/logging.vsl
  examples/config/minimal.vsl
  examples/config/secured.vsl
  examples/config/simple.vsl
  examples/config/tls.vsl
  src/vqueue/Cargo.toml
  src/vsmtp/plugins/vsmtp-plugin-vsl/Cargo.toml
  src/vsmtp/vsmtp-auth/Cargo.toml
  src/vsmtp/vsmtp-common/Cargo.toml
  src/vsmtp/vsmtp-config/Cargo.toml
  src/vsmtp/vsmtp-core/Cargo.toml
  src/vsmtp/vsmtp-delivery/Cargo.toml
  src/vsmtp/vsmtp-docs/Cargo.toml
  src/vsmtp/vsmtp-mail-parser/Cargo.toml
  src/vsmtp/vsmtp-protocol/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/Cargo.toml
  src/vsmtp/vsmtp-server/Cargo.toml
  src/vsmtp/vsmtp-test/Cargo.toml
Labels: B-candidate

#800 Fix<ci>: fuzz & pre-release check (vsl plugins)
  .github/workflows/pre-release.yaml
  .github/workflows/staging.yaml
  fuzz/Cargo.lock
  fuzz/server/vsmtp.vsl
Labels: A-ci

#799 Staging v1.4.0-rc.4
  .github/workflows/pre-release.yaml
  .github/workflows/staging.yaml
  Cargo.lock
  examples/antivirus/vsmtp.vsl
  examples/config/auth.vsl
  examples/config/complete.vsl
  examples/config/logging.vsl
  examples/config/minimal.vsl
  examples/config/secured.vsl
  examples/config/simple.vsl
  examples/config/tls.vsl
  fuzz/Cargo.lock
  fuzz/server/vsmtp.vsl
  src/vqueue/Cargo.toml
  src/vsmtp/plugins/vsmtp-plugin-vsl/Cargo.toml
  src/vsmtp/vsmtp-auth/Cargo.toml
  src/vsmtp/vsmtp-common/Cargo.toml
  src/vsmtp/vsmtp-config/Cargo.toml
  src/vsmtp/vsmtp-core/Cargo.toml
  src/vsmtp/vsmtp-delivery/Cargo.toml
  src/vsmtp/vsmtp-docs/Cargo.toml
  src/vsmtp/vsmtp-mail-parser/Cargo.toml
  src/vsmtp/vsmtp-protocol/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/Cargo.toml
  src/vsmtp/vsmtp-server/Cargo.toml
  src/vsmtp/vsmtp-test/Cargo.toml
Labels: B-candidate

#801 Release v1.4.0-rc.4
  .github/workflows/pre-release.yaml
  .github/workflows/staging.yaml
  Cargo.lock
  examples/antivirus/vsmtp.vsl
  examples/config/auth.vsl
  examples/config/complete.vsl
  examples/config/logging.vsl
  examples/config/minimal.vsl
  examples/config/secured.vsl
  examples/config/simple.vsl
  examples/config/tls.vsl
  fuzz/Cargo.lock
  fuzz/server/vsmtp.vsl
  src/vqueue/Cargo.toml
  src/vsmtp/plugins/vsmtp-plugin-vsl/Cargo.toml
  src/vsmtp/vsmtp-auth/Cargo.toml
  src/vsmtp/vsmtp-common/Cargo.toml
  src/vsmtp/vsmtp-config/Cargo.toml
  src/vsmtp/vsmtp-core/Cargo.toml
  src/vsmtp/vsmtp-delivery/Cargo.toml
  src/vsmtp/vsmtp-docs/Cargo.toml
  src/vsmtp/vsmtp-mail-parser/Cargo.toml
  src/vsmtp/vsmtp-protocol/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/Cargo.toml
  src/vsmtp/vsmtp-server/Cargo.toml
  src/vsmtp/vsmtp-test/Cargo.toml
Labels: B-candidate

#802 fix<ci>: release no cache + verbose
  .github/workflows/post-release.yaml
  .github/workflows/release.yml
  Cargo.lock
  examples/antivirus/vsmtp.vsl
  examples/config/auth.vsl
  examples/config/complete.vsl
  examples/config/logging.vsl
  examples/config/minimal.vsl
  examples/config/secured.vsl
  examples/config/simple.vsl
  examples/config/tls.vsl
  fuzz/server/vsmtp.vsl
  src/vqueue/Cargo.toml
  src/vsmtp/plugins/vsmtp-plugin-vsl/Cargo.toml
  src/vsmtp/vsmtp-auth/Cargo.toml
  src/vsmtp/vsmtp-common/Cargo.toml
  src/vsmtp/vsmtp-config/Cargo.toml
  src/vsmtp/vsmtp-core/Cargo.toml
  src/vsmtp/vsmtp-delivery/Cargo.toml
  src/vsmtp/vsmtp-docs/Cargo.toml
  src/vsmtp/vsmtp-mail-parser/Cargo.toml
  src/vsmtp/vsmtp-protocol/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/Cargo.toml
  src/vsmtp/vsmtp-server/Cargo.toml
  src/vsmtp/vsmtp-test/Cargo.toml
Labels: A-ci

#805 Staging next candidate (rc5)
  .github/workflows/post-release.yaml
  .github/workflows/release.yml
  Cargo.lock
  examples/antivirus/vsmtp.vsl
  examples/config/auth.vsl
  examples/config/complete.vsl
  examples/config/logging.vsl
  examples/config/minimal.vsl
  examples/config/secured.vsl
  examples/config/simple.vsl
  examples/config/tls.vsl
  fuzz/server/vsmtp.vsl
  src/vqueue/Cargo.toml
  src/vsmtp/plugins/vsmtp-plugin-vsl/Cargo.toml
  src/vsmtp/vsmtp-auth/Cargo.toml
  src/vsmtp/vsmtp-common/Cargo.toml
  src/vsmtp/vsmtp-config/Cargo.toml
  src/vsmtp/vsmtp-core/Cargo.toml
  src/vsmtp/vsmtp-delivery/Cargo.toml
  src/vsmtp/vsmtp-docs/Cargo.toml
  src/vsmtp/vsmtp-mail-parser/Cargo.toml
  src/vsmtp/vsmtp-protocol/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/Cargo.toml
  src/vsmtp/vsmtp-server/Cargo.toml
  src/vsmtp/vsmtp-test/Cargo.toml
Labels: A-ci

#815 fix: update the authenticate api function
  src/vsmtp/vsmtp-config/src/ensure.rs
  src/vsmtp/vsmtp-rule-engine/api/auth.rhai
Labels: A-vsl

#817 Revert: `auth_unix_users` does not assert `RFC5321.MailFrom == authid`
  src/vsmtp/vsmtp-rule-engine/api/auth.rhai
Labels: A-security

#819 Use tls for delivery
  Cargo.lock
  benchmarks/stress/Cargo.toml
  src/vqueue/Cargo.toml
  src/vsmtp/plugins/vsmtp-plugin-vsl/Cargo.toml
  src/vsmtp/vsmtp-auth/Cargo.toml
  src/vsmtp/vsmtp-common/Cargo.toml
  src/vsmtp/vsmtp-config/Cargo.toml
  src/vsmtp/vsmtp-config/src/builder/with.rs
  src/vsmtp/vsmtp-config/src/parser/tls_certificate.rs
  src/vsmtp/vsmtp-config/src/parser/tls_private_key.rs
  src/vsmtp/vsmtp-config/src/tests/root_example/tls.rs
  src/vsmtp/vsmtp-config/src/virtual_tls.rs
  src/vsmtp/vsmtp-core/Cargo.toml
  src/vsmtp/vsmtp-delivery/Cargo.toml
  src/vsmtp/vsmtp-delivery/src/lib.rs
  src/vsmtp/vsmtp-delivery/src/sender.rs
  src/vsmtp/vsmtp-delivery/src/transport/deliver.rs
  src/vsmtp/vsmtp-delivery/src/transport/forward.rs
  src/vsmtp/vsmtp-docs/Cargo.toml
  src/vsmtp/vsmtp-mail-parser/Cargo.toml
  src/vsmtp/vsmtp-protocol/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/Cargo.toml
  src/vsmtp/vsmtp-server/Cargo.toml
  src/vsmtp/vsmtp-test/Cargo.toml
  src/vsmtp/vsmtp-test/src/config.rs
  src/vsmtp/vsmtp-test/src/tests/mod.rs
  src/vsmtp/vsmtp-test/src/tests/protocol/tls/cipher_suite.rs
  src/vsmtp/vsmtp-test/src/tests/protocol/tls/mod.rs
  src/vsmtp/vsmtp-test/src/tests/protocol/tls/starttls.rs
  src/vsmtp/vsmtp-test/src/tests/protocol/tls/tunneled.rs
  src/vsmtp/vsmtp-test/src/tests/protocol/tls/tunneled_with_auth.rs
Labels: A-delivery

#821 Enhance staging tests
  src/vsmtp/vsmtp-rule-engine/src/rule_engine.rs
  src/vsmtp/vsmtp-test/tests/mod.rs
Labels: A-ci, A-test

#822 fix: --help for vqueue & vsmtp
  Cargo.lock
  src/vqueue/Cargo.toml
  src/vqueue/src/cli/args.rs
  src/vsmtp/vsmtp-core/Cargo.toml
Labels: A-queue

#825 Feat: mask credentials on release build
  src/vsmtp/vsmtp-common/src/auth/credentials.rs
Labels: A-security

#829 Update delegation return logics
  .vscode/settings.json
  src/vqueue/src/api.rs
  src/vqueue/src/extension.rs
  src/vqueue/src/implementation/fs.rs
  src/vqueue/src/implementation/temp.rs
  src/vqueue/src/lib.rs
  src/vsmtp/plugins/vsmtp-plugin-vsl/src/api.rs
  src/vsmtp/vsmtp-auth/src/dkim/public_key.rs
  src/vsmtp/vsmtp-auth/src/spf/mod.rs
  src/vsmtp/vsmtp-common/src/status.rs
  src/vsmtp/vsmtp-common/src/types/client_name.rs
  src/vsmtp/vsmtp-config/src/builder/validate.rs
  src/vsmtp/vsmtp-config/src/lib.rs
  src/vsmtp/vsmtp-config/src/parser/syst_group.rs
  src/vsmtp/vsmtp-config/src/parser/syst_user.rs
  src/vsmtp/vsmtp-core/src/main.rs
  src/vsmtp/vsmtp-core/src/tracing_subscriber.rs
  src/vsmtp/vsmtp-delivery/src/lib.rs
  src/vsmtp/vsmtp-delivery/src/send.rs
  src/vsmtp/vsmtp-delivery/src/transport/deliver.rs
  src/vsmtp/vsmtp-delivery/src/transport/forward.rs
  src/vsmtp/vsmtp-delivery/src/transport/maildir.rs
  src/vsmtp/vsmtp-docs/src/main.rs
  src/vsmtp/vsmtp-mail-parser/src/helpers.rs
  src/vsmtp/vsmtp-mail-parser/src/message/mail.rs
  src/vsmtp/vsmtp-protocol/src/receiver.rs
  src/vsmtp/vsmtp-protocol/src/smtp_sasl.rs
  src/vsmtp/vsmtp-rule-engine/src/api/rule_state.rs
  src/vsmtp/vsmtp-rule-engine/src/api/transports.rs
  src/vsmtp/vsmtp-rule-engine/src/api/types.rs
  src/vsmtp/vsmtp-rule-engine/src/dsl/directives/action.rs
  src/vsmtp/vsmtp-rule-engine/src/dsl/directives/delegation.rs
  src/vsmtp/vsmtp-rule-engine/src/dsl/directives/mod.rs
  src/vsmtp/vsmtp-rule-engine/src/dsl/directives/rule.rs
  src/vsmtp/vsmtp-rule-engine/src/error.rs
  src/vsmtp/vsmtp-rule-engine/src/lib.rs
  src/vsmtp/vsmtp-rule-engine/src/rule_engine.rs
  src/vsmtp/vsmtp-server/benches/iai/receiver.rs
  src/vsmtp/vsmtp-server/benches/receiver2.rs
  src/vsmtp/vsmtp-server/src/processing/mod.rs
  src/vsmtp/vsmtp-server/src/receiver/handler.rs
  src/vsmtp/vsmtp-server/src/receiver/post_transaction.rs
  src/vsmtp/vsmtp-server/src/receiver/pre_transaction.rs
  src/vsmtp/vsmtp-server/src/server.rs
  src/vsmtp/vsmtp-test/src/receiver.rs
  src/vsmtp/vsmtp-test/src/tests/vqueue/mod.rs
Labels: A-rule-engine, P-medium, C-refactoring

#835 Default filtering rules
  src/vsmtp/vsmtp-rule-engine/src/sub_domain_hierarchy.rs
Labels: C-bug

#836 Update `TLS.certificate` & SNI
  Cargo.lock
  src/vsmtp/vsmtp-common/src/transfer.rs
  src/vsmtp/vsmtp-config/Cargo.toml
  src/vsmtp/vsmtp-config/src/builder/with.rs
  src/vsmtp/vsmtp-config/src/config.rs
  src/vsmtp/vsmtp-config/src/parser/tls_certificate.rs
  src/vsmtp/vsmtp-config/src/rustls_helper.rs
  src/vsmtp/vsmtp-config/src/virtual_tls.rs
  src/vsmtp/vsmtp-delivery/Cargo.toml
  src/vsmtp/vsmtp-delivery/src/lib.rs
  src/vsmtp/vsmtp-delivery/src/sender.rs
  src/vsmtp/vsmtp-delivery/src/transport/deliver.rs
  src/vsmtp/vsmtp-delivery/src/transport/forward.rs
  src/vsmtp/vsmtp-test/src/tests/protocol/tls/starttls.rs
  src/vsmtp/vsmtp-test/src/tests/protocol/tls/tunneled.rs
  src/vsmtp/vsmtp-test/src/tests/protocol/tls/tunneled_with_auth.rs
Labels: P-medium, A-protocol

#839 Remove 'root' tls & dkim parameters
  examples/anti_relaying/conf.d/config.vsl
  examples/config/tls.vsl
  examples/family/vsmtp.vsl
  examples/message/conf.d/config.vsl
  src/vsmtp/vsmtp-config/src/builder/validate.rs
  src/vsmtp/vsmtp-config/src/builder/with.rs
  src/vsmtp/vsmtp-config/src/config.rs
  src/vsmtp/vsmtp-config/src/default.rs
  src/vsmtp/vsmtp-config/src/rustls_helper.rs
  src/vsmtp/vsmtp-config/src/tests/root_example/tls.rs
  src/vsmtp/vsmtp-delivery/src/lib.rs
  src/vsmtp/vsmtp-delivery/src/transport/forward.rs
  src/vsmtp/vsmtp-rule-engine/src/api/dkim.rs
  src/vsmtp/vsmtp-rule-engine/src/api/utils.rs
  src/vsmtp/vsmtp-test/src/config.rs
  src/vsmtp/vsmtp-test/src/tests/protocol/tls/starttls.rs
  src/vsmtp/vsmtp-test/src/tests/protocol/tls/tunneled_with_auth.rs
  src/vsmtp/vsmtp-test/tests/mod.rs
Labels: A-config, A-ci

#841 Replace filepath by filename for log paths
  examples/config/auth.vsl
  examples/config/complete.vsl
  examples/config/logging.vsl
  fuzz/server/vsmtp.vsl
  src/vsmtp/vsmtp-config/src/builder/validate.rs
  src/vsmtp/vsmtp-config/src/builder/wants.rs
  src/vsmtp/vsmtp-config/src/builder/with.rs
  src/vsmtp/vsmtp-config/src/config.rs
  src/vsmtp/vsmtp-config/src/default.rs
  src/vsmtp/vsmtp-config/src/ensure.rs
  src/vsmtp/vsmtp-core/src/main.rs
  src/vsmtp/vsmtp-core/src/tracing_subscriber.rs
  src/vsmtp/vsmtp-rule-engine/src/lib.rs
Labels: A-config

#844 ci: set explicit permission read/write
  .github/workflows/benchmark.yaml
  .github/workflows/ci.yaml
  .github/workflows/post-release.yaml
  .github/workflows/pre-release.yaml
  .github/workflows/release.yml
  .github/workflows/staging.yaml
Labels: A-ci

#846 Fix: ci release use `fetch-depth: 0` to make `cargo-release` work fine
  .github/workflows/pre-release.yaml
  .github/workflows/release.yml
Labels: A-ci

#845 Staging next candidate (rc7)
  .github/workflows/benchmark.yaml
  .github/workflows/ci.yaml
  .github/workflows/post-release.yaml
  .github/workflows/pre-release.yaml
  .github/workflows/release.yml
  .github/workflows/staging.yaml
  Cargo.lock
  examples/antivirus/vsmtp.vsl
  examples/config/auth.vsl
  examples/config/complete.vsl
  examples/config/logging.vsl
  examples/config/minimal.vsl
  examples/config/secured.vsl
  examples/config/simple.vsl
  examples/config/tls.vsl
  fuzz/server/vsmtp.vsl
  src/vqueue/Cargo.toml
  src/vsmtp/plugins/vsmtp-plugin-vsl/Cargo.toml
  src/vsmtp/vsmtp-auth/Cargo.toml
  src/vsmtp/vsmtp-common/Cargo.toml
  src/vsmtp/vsmtp-config/Cargo.toml
  src/vsmtp/vsmtp-core/Cargo.toml
  src/vsmtp/vsmtp-delivery/Cargo.toml
  src/vsmtp/vsmtp-docs/Cargo.toml
  src/vsmtp/vsmtp-mail-parser/Cargo.toml
  src/vsmtp/vsmtp-protocol/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/Cargo.toml
  src/vsmtp/vsmtp-server/Cargo.toml
  src/vsmtp/vsmtp-test/Cargo.toml
Labels: B-candidate

#855 Release v1.4.0-rc.7
  .github/workflows/benchmark.yaml
  .github/workflows/ci.yaml
  .github/workflows/post-release.yaml
  .github/workflows/pre-release.yaml
  .github/workflows/release.yml
  .github/workflows/staging.yaml
  Cargo.lock
  examples/antivirus/vsmtp.vsl
  examples/config/auth.vsl
  examples/config/complete.vsl
  examples/config/logging.vsl
  examples/config/minimal.vsl
  examples/config/secured.vsl
  examples/config/simple.vsl
  examples/config/tls.vsl
  fuzz/server/vsmtp.vsl
  src/vqueue/Cargo.toml
  src/vsmtp/plugins/vsmtp-plugin-vsl/Cargo.toml
  src/vsmtp/vsmtp-auth/Cargo.toml
  src/vsmtp/vsmtp-common/Cargo.toml
  src/vsmtp/vsmtp-config/Cargo.toml
  src/vsmtp/vsmtp-core/Cargo.toml
  src/vsmtp/vsmtp-delivery/Cargo.toml
  src/vsmtp/vsmtp-docs/Cargo.toml
  src/vsmtp/vsmtp-mail-parser/Cargo.toml
  src/vsmtp/vsmtp-protocol/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/Cargo.toml
  src/vsmtp/vsmtp-server/Cargo.toml
  src/vsmtp/vsmtp-test/Cargo.toml
Labels: B-candidate

#856 Ci release minor improvement
  .github/workflows/ci.yaml
  .github/workflows/post-release.yaml
  .github/workflows/release.yaml
  release.toml
Labels: A-ci

#860 Vsl scripts root is placed in the directory of the config
  src/vsmtp/vsmtp-rule-engine/src/rule_engine.rs
Labels: C-bug

#861 Fix sender tls domain / relay target
  src/vsmtp/vsmtp-delivery/src/sender.rs
  src/vsmtp/vsmtp-delivery/src/transport/deliver.rs
  src/vsmtp/vsmtp-delivery/src/transport/forward.rs
Labels: C-bug

#864 Document `dependencies & features`
  Cargo.lock
  src/vsmtp/vsmtp-core/Cargo.toml
  src/vsmtp/vsmtp-core/src/lib.rs
Labels: C-documentation

#866 Support null reverse path `MAIL FROM:<>`
  src/vqueue/src/cli/debugger/message_show.rs
  src/vsmtp/vsmtp-auth/src/lib.rs
  src/vsmtp/vsmtp-common/src/context.rs
  src/vsmtp/vsmtp-delivery/src/lib.rs
  src/vsmtp/vsmtp-delivery/src/transport/deliver.rs
  src/vsmtp/vsmtp-delivery/src/transport/forward.rs
  src/vsmtp/vsmtp-delivery/src/transport/maildir.rs
  src/vsmtp/vsmtp-delivery/src/transport/mbox.rs
  src/vsmtp/vsmtp-protocol/src/command.rs
  src/vsmtp/vsmtp-rule-engine/src/api/dkim.rs
  src/vsmtp/vsmtp-rule-engine/src/api/dmarc.rs
  src/vsmtp/vsmtp-rule-engine/src/api/mail_context.rs
  src/vsmtp/vsmtp-rule-engine/src/api/spf.rs
  src/vsmtp/vsmtp-rule-engine/src/api/utils.rs
  src/vsmtp/vsmtp-rule-engine/src/lib.rs
  src/vsmtp/vsmtp-rule-engine/src/rule_engine.rs
  src/vsmtp/vsmtp-server/src/lib.rs
  src/vsmtp/vsmtp-server/src/receiver/handler.rs
  src/vsmtp/vsmtp-test/src/config.rs
  src/vsmtp/vsmtp-test/src/tests/examples/message.rs
  src/vsmtp/vsmtp-test/src/tests/protocol/auth/basic.rs
  src/vsmtp/vsmtp-test/src/tests/protocol/clair.rs
  src/vsmtp/vsmtp-test/src/tests/protocol/mail_from.rs
  src/vsmtp/vsmtp-test/src/tests/protocol/rset.rs
  src/vsmtp/vsmtp-test/src/tests/protocol/utf8.rs
  src/vsmtp/vsmtp-test/src/tests/rule_engine/getters.rs
Labels: A-protocol

#869 vsl: add `to_string` for `ctx()` and `msg()`
  src/vsmtp/vsmtp-rule-engine/src/api/mail_context.rs
  src/vsmtp/vsmtp-rule-engine/src/api/message.rs
  src/vsmtp/vsmtp-rule-engine/src/rule_engine.rs
Labels: A-vsl
