Repository viridIT/vSMTP, pull requests merged in 2022-01, with the labels that each got.

#51 ESMTP 8BITMIME + SMTPUTF8
  .vscode/settings.json
  Cargo.toml
  TESTING.md
  config/vsmtp.default.toml
  src/config/custom_code.rs
  src/mailprocessing/mail_receiver.rs
  src/smtp/code.rs
  src/smtp/event.rs
  tests/integration/protocol/clair.rs
  tests/integration/protocol/utf8.rs
Labels: enhancement, tests, P-high

#61 refact: change process_event output and where on_data_end is called
  src/config/server_config.rs
  src/mailprocessing/mail_receiver.rs
  src/mailprocessing/mod.rs
  src/mailprocessing/state.rs
  src/model/mail.rs
Labels: architecture, P-high

#64 Refact/receiver2
  .vscode/settings.json
  Cargo.toml
  benches/receiver.rs
  fuzz/fuzz_targets/receiver.rs
  src/config/server_config.rs
  src/connection.rs
  src/io_service.rs
  src/lib.rs
  src/mailprocessing/mail_receiver.rs
  src/mailprocessing/mod.rs
  src/main.rs
  src/model/envelop.rs
  src/model/mail.rs
  src/rules/actions.rs
  src/rules/currying.rhai
  src/rules/mod.rs
  src/rules/rule_engine.rs
  src/rules/tests/mod.rs
  src/server.rs
  src/smtp/mod.rs
  src/smtp/state.rs
  src/test_helpers.rs
  src/transaction.rs
  tests/integration/protocol/clair.rs
  tests/integration/protocol/mod.rs
  tests/integration/protocol/rset.rs
  tests/integration/protocol/utf8.rs
Labels: enhancement, architecture, tests, delivery

#65 Refact/resolver
  .vscode/settings.json
  Cargo.toml
  benches/receiver.rs
  src/config/server_config.rs
  src/main.rs
  src/resolver.rs
  src/resolver/maildir_resolver.rs
  src/rules/tests/connect.rs
  src/rules/tests/helo.rs
  src/rules/tests/mail.rs
  src/rules/tests/mod.rs
  src/rules/tests/rcpt.rs
  src/server.rs
  src/test_helpers.rs
  tests/dos/mod.rs
  tests/integration/protocol/clair.rs
  tests/integration/protocol/rset.rs
  tests/integration/protocol/utf8.rs
Labels: enhancement, architecture, P-high, delivery, mime

#66 Feat/reverse lookup#63
  Cargo.toml
  src/resolver.rs
  src/rules/actions.rs
  src/rules/currying.rhai
  src/rules/rule_engine.rs
  src/rules/tests/mod.rs
  src/rules/tests/r_lookup.rs
  src/rules/tests/rules/actions/r_lookup.vsl
  src/rules/tests/rules/actions/r_lookup_failure.vsl
  src/test_helpers.rs
Labels: enhancement, rule engine

#69 SSL/TLS protocol version requirement in config
  .vscode/settings.json
  benches/bench.config.toml
  benches/receiver.rs
  config/vsmtp.default.toml
  config/vsmtp.dev-local.toml
  fuzz/Cargo.toml
  fuzz/fuzz_targets/fuzz.config.toml
  fuzz/fuzz_targets/receiver.rs
  src/config/mod.rs
  src/config/serializer.rs
  src/config/server_config.rs
  src/connection.rs
  src/lib.rs
  src/resolver/maildir_resolver.rs
  src/rules/actions.rs
  src/rules/rule_engine.rs
  src/rules/tests/configs/default.config.toml
  src/rules/tests/mod.rs
  src/server.rs
  src/test_helpers.rs
  src/tls.rs
  src/transaction.rs
  tests/integration/protocol/clair.config.toml
  tests/integration/protocol/clair.rs
  tests/integration/protocol/mod.rs
Labels: bug, enhancement, P-medium

#70 Feat/deliver process#55
  Cargo.toml
  src/config/mod.rs
  src/main.rs
  src/resolver/maildir_resolver.rs
  src/rules/rule_engine.rs
  src/server.rs
Labels: architecture, P-high, delivery

#71 refact: move queue resolver in right folder
  src/main.rs
  src/resolver.rs
  src/resolver/deliver_queue.rs
  src/server.rs
Labels: P-medium

#73 Mime Parsing
  fuzz/Cargo.toml
  fuzz/fuzz_targets/mime_parser.rs
  src/lib.rs
  src/mime/error.rs
  src/mime/mail.rs
  src/mime/mime_type.rs
  src/mime/mod.rs
  src/mime/parser.rs
  src/mime/tests/mail/allen-p__discussion_threads__1.
  src/mime/tests/mail/buy-r__discussion_threads__10.
  src/mime/tests/mail/buy-r__discussion_threads__12.
  src/mime/tests/mail/buy-r__discussion_threads__54.
  src/mime/tests/mail/dorland-c__sent_items__66.
  src/mime/tests/mime_parser/allen_p__discussion_threads__1.rs
  src/mime/tests/mod.rs
Labels: enhancement, tests, P-critical, mime

#74 vMIME process
  config/vsmtp.dev-local.toml
  src/main.rs
  src/resolver/deliver_queue.rs
Labels: enhancement, architecture, P-critical, delivery, mime

#76 Parser integration
  benches/receiver.rs
  src/main.rs
  src/mime/error.rs
  src/mime/mail.rs
  src/mime/mime_type.rs
  src/mime/mod.rs
  src/model/mail.rs
  src/resolver/maildir_resolver.rs
  src/rules/actions.rs
  src/transaction.rs
  tests/integration/protocol/clair.rs
  tests/integration/protocol/rset.rs
  tests/integration/protocol/utf8.rs
Labels: architecture, mime

#78 Deferred Queue #1
  .vscode/settings.json
  config/vsmtp.dev-local.toml
  src/main.rs
  src/resolver/deliver_queue.rs
  src/resolver/maildir_resolver.rs
  src/server.rs
Labels: enhancement, delivery

#79 Dead queue #1
  benches/bench.config.toml
  config/vsmtp.default.toml
  config/vsmtp.dev-local.toml
  src/config/server_config.rs
  src/main.rs
  src/rules/tests/configs/default.config.toml
  tests/integration/protocol/clair.config.toml
Labels: enhancement, delivery

#81 Cronjob for flushing Deferred Queue
  .github/workflows/ci.yaml
  Cargo.toml
  config/vsmtp.default.toml
  config/vsmtp.dev-local.toml
  src/config/server_config.rs
  src/main.rs
  src/resolver/deliver_queue.rs
  src/rules/address.rs
  tests/dos/mod.rs
Labels: enhancement, P-high, delivery

#85 Feat/mail rewrite#67
  benches/receiver.rs
  src/main.rs
  src/mime/mail.rs
  src/rules/actions.rs
  src/rules/currying.rhai
  src/rules/rule_engine.rs
  src/rules/tests/mail.rs
  src/rules/tests/mod.rs
  src/rules/tests/rcpt.rs
  src/rules/tests/rules/mail/rw_mail.vsl
  src/rules/tests/rules/rcpt/add_rcpt.vsl
  src/rules/tests/rules/rcpt/rm_rcpt.vsl
  src/rules/tests/rules/rcpt/rw_rcpt.vsl
  src/test_helpers.rs
  src/transaction.rs
  tests/integration/protocol/clair.rs
  tests/integration/protocol/mail/ar.txt
  tests/integration/protocol/mail/el.txt
  tests/integration/protocol/mail/ko.txt
  tests/integration/protocol/mail/zh.txt
  tests/integration/protocol/rset.rs
  tests/integration/protocol/utf8.rs
Labels: rule engine, P-high, mime

#89 refact: cleanup how timeout are parsed (config.toml is not changed)
  config/vsmtp.dev-local.toml
  src/config/server_config.rs
  src/transaction.rs
Labels: documentation, enhancement

#90 Feat/smtp client#72
  Cargo.toml
  src/main.rs
  src/resolver.rs
  src/resolver/smtp_resolver.rs
Labels: delivery, mime

#93 CONTAINS_RCPT action
  src/rules/actions.rs
  src/rules/currying.rhai
  src/rules/tests/rcpt.rs
  src/rules/tests/rules/rcpt/contains_rcpt.vsl
  src/transaction.rs
Labels: rule engine, vsl

#94 Refact/processes
  src/lib.rs
  src/main.rs
  src/processes/delivery.rs
  src/processes/mime.rs
  src/processes/mod.rs
  src/queue.rs
  src/resolver/deliver_queue.rs
  src/resolver/smtp_resolver.rs
  src/server.rs
  src/test_helpers.rs
  tests/dos/mod.rs
Labels: architecture

#95 Feat/postq#87
  src/main.rs
  src/model/mail.rs
  src/processes/delivery.rs
  src/processes/mime.rs
  src/processes/mod.rs
  src/queue.rs
  src/resolver/deliver_queue.rs
  src/resolver/maildir_resolver.rs
  src/resolver/mod.rs
  src/resolver/smtp_resolver.rs
  src/rules/currying.rhai
  src/rules/rule_engine.rs
  src/server.rs
  src/test_helpers.rs
  src/transaction.rs
  tests/dos/mod.rs
Labels: rule engine, vsl

#99 MBox Resolver
  Cargo.toml
  src/main.rs
  src/processes/mime.rs
  src/resolver/maildir_resolver.rs
  src/resolver/mbox_resolver.rs
  src/resolver/mod.rs
  src/rules/currying.rhai
Labels: rule engine, delivery, vsl

#100 Lookup mail from
  Cargo.toml
  benches/receiver.rs
  src/rules/actions.rs
  src/rules/address.rs
  src/rules/currying.rhai
  src/rules/rule_engine.rs
  src/rules/tests/connect.rs
  src/rules/tests/helo.rs
  src/rules/tests/mail.rs
  src/rules/tests/mod.rs
  src/rules/tests/r_lookup.rs
  src/rules/tests/rcpt.rs
  src/rules/tests/rules/actions/r_lookup.vsl
  src/rules/tests/rules/actions/r_lookup_failure.vsl
  src/rules/tests/rules/connect/invalid_connect.vsl
  src/rules/tests/rules/connect/valid_connect.vsl
  src/test_helpers.rs
  tests/integration/protocol/clair.rs
  tests/integration/protocol/rset.rs
  tests/integration/protocol/utf8.rs
Labels: rule engine, vsl

#101 Anyhow
  Cargo.toml
  benches/receiver.rs
  src/config/mod.rs
  src/connection.rs
  src/main.rs
  src/mime/error.rs
  src/processes/delivery.rs
  src/processes/mime.rs
  src/queue.rs
  src/resolver/maildir_resolver.rs
  src/resolver/mbox_resolver.rs
  src/resolver/mod.rs
  src/resolver/smtp_resolver.rs
  src/rules/obj.rs
  src/rules/rule_engine.rs
  src/rules/tests/mail.rs
  src/rules/tests/mod.rs
  src/rules/tests/rcpt.rs
  src/server.rs
  src/test_helpers.rs
  src/tls.rs
  src/transaction.rs
  tests/integration/protocol/clair.rs
  tests/integration/protocol/rset.rs
  tests/integration/protocol/utf8.rs
Labels: architecture, P-low

#102 Quarantine
  Cargo.toml
  src/processes/mime.rs
  src/queue.rs
  src/rules/actions.rs
  src/rules/currying.rhai
  src/rules/operation_queue.rs
  src/rules/rule_engine.rs
  src/server.rs
  src/transaction.rs
Labels: rule engine, delivery, vsl

#104 Coverage
  .github/actions-rs/grcov.yml
  .github/workflows/ci.yaml
Labels: documentation, tests, P-high

#105 test: add plain and starttls sender test
  tests/send.rs
Labels: tests, P-high
