Repository viridIT/vSMTP, pull requests merged in 2022-07, with the labels that each got.

#416 Fix: lints from version 1.62
  src/vsmtp/vsmtp-common/src/queue.rs
  src/vsmtp/vsmtp-mail-parser/src/helpers.rs
  src/vsmtp/vsmtp-server/src/runtime.rs
  src/vsmtp/vsmtp-test/src/receiver.rs
Labels: P-medium

#418 Refactoring Spf
  examples/config/auth/main.vsl
  src/vsmtp/vsmtp-rule-engine/src/api/auth.rhai
  src/vsmtp/vsmtp-rule-engine/src/modules/actions/security.rs
Labels: A-vsl

#419 SPF identity
  src/vsmtp/vsmtp-rule-engine/src/api/auth.rhai
  src/vsmtp/vsmtp-rule-engine/src/modules/actions/security.rs
Labels: A-vsl

#423 SPF Refactor
  src/vsmtp/vsmtp-rule-engine/src/api/auth.rhai
  src/vsmtp/vsmtp-rule-engine/src/modules/actions/security.rs
Labels: A-vsl

#425 Simplify queue logics
  Cargo.lock
  src/vqueue/src/command/mod.rs
  src/vqueue/src/command/msg_command/show.rs
  src/vqueue/src/command/queue_show.rs
  src/vsmtp/vsmtp-common/src/queue.rs
  src/vsmtp/vsmtp-common/src/rcpt.rs
  src/vsmtp/vsmtp-common/src/transfer.rs
  src/vsmtp/vsmtp-delivery/src/lib.rs
  src/vsmtp/vsmtp-delivery/src/transport/deliver.rs
  src/vsmtp/vsmtp-delivery/src/transport/forward.rs
  src/vsmtp/vsmtp-delivery/src/transport/maildir.rs
  src/vsmtp/vsmtp-delivery/src/transport/mbox.rs
  src/vsmtp/vsmtp-rule-engine/src/tests/rules.rs
  src/vsmtp/vsmtp-server/Cargo.toml
  src/vsmtp/vsmtp-server/src/delivery/deferred.rs
  src/vsmtp/vsmtp-server/src/delivery/deliver.rs
  src/vsmtp/vsmtp-server/src/delivery/mod.rs
  src/vsmtp/vsmtp-server/src/lib.rs
  src/vsmtp/vsmtp-server/src/processing/mod.rs
  src/vsmtp/vsmtp-test/src/tests/rules/quarantine/mod.rs
Labels: A-delivery, A-queue

#427 Delivery Fix
  src/vsmtp/vsmtp-delivery/src/transport/deliver.rs
Labels: C-bug

#378 Doc config
  examples/config/complete.toml
  examples/config/secured.toml
  src/vsmtp/vsmtp-config/src/config.rs
  src/vsmtp/vsmtp-config/src/lib.rs
Labels: C-documentation, P-medium, A-config

#438 Delegation Header
  CHANGELOG.md
  Cargo.lock
  src/vqueue/src/command/queue_show.rs
  src/vsmtp/vsmtp-common/src/mail_context.rs
  src/vsmtp/vsmtp-common/src/message/mail.rs
  src/vsmtp/vsmtp-common/src/queue.rs
  src/vsmtp/vsmtp-common/src/state.rs
  src/vsmtp/vsmtp-common/src/status.rs
  src/vsmtp/vsmtp-common/src/transfer.rs
  src/vsmtp/vsmtp-mail-parser/src/lib.rs
  src/vsmtp/vsmtp-mail-parser/src/parser.rs
  src/vsmtp/vsmtp-rule-engine/src/dsl/directives.rs
  src/vsmtp/vsmtp-rule-engine/src/dsl/service/mod.rs
  src/vsmtp/vsmtp-rule-engine/src/dsl/service/smtp.rs
  src/vsmtp/vsmtp-rule-engine/src/error.rs
  src/vsmtp/vsmtp-rule-engine/src/modules/message.rs
  src/vsmtp/vsmtp-rule-engine/src/rule_engine.rs
  src/vsmtp/vsmtp-rule-engine/src/rule_state.rs
  src/vsmtp/vsmtp-server/Cargo.toml
  src/vsmtp/vsmtp-server/src/channel_message.rs
  src/vsmtp/vsmtp-server/src/delivery/deferred.rs
  src/vsmtp/vsmtp-server/src/delivery/deliver.rs
  src/vsmtp/vsmtp-server/src/delivery/mod.rs
  src/vsmtp/vsmtp-server/src/lib.rs
  src/vsmtp/vsmtp-server/src/processing/mod.rs
  src/vsmtp/vsmtp-server/src/receiver/mod.rs
  src/vsmtp/vsmtp-server/src/receiver/on_mail.rs
  src/vsmtp/vsmtp-server/src/receiver/transaction.rs
  tools/install/deb/changelog
Labels: A-vsl

#442 Ubuntu 20 & 22
  .github/workflows/post-release.yaml
  .github/workflows/pre-release.yaml
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  src/vqueue/Cargo.toml
  src/vsmtp/vsmtp-common/Cargo.toml
  src/vsmtp/vsmtp-config/Cargo.toml
  src/vsmtp/vsmtp-delivery/Cargo.toml
  src/vsmtp/vsmtp-mail-parser/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/Cargo.toml
  src/vsmtp/vsmtp-server/Cargo.toml
  src/vsmtp/vsmtp-test/Cargo.toml
Labels: A-ci

#445 Delegation Cleanup
  src/vsmtp/vsmtp-server/src/processing/mod.rs
  src/vsmtp/vsmtp-server/src/receiver/on_mail.rs
Labels: A-rule-engine, P-low

#446 fix: use dnssec-ring instead of dnssec-openssl
  Cargo.lock
  src/vsmtp/vsmtp-delivery/Cargo.toml
  src/vsmtp/vsmtp-server/Cargo.toml
Labels: C-enhancement, P-medium, A-dependencies

#426 deps: bump rhai v1.8.0 and remove doc_hidden
  .github/workflows/ci.yaml
  Cargo.lock
  Cargo.toml
  README.md
  benchmarks/stress/Cargo.toml
  src/vqueue/Cargo.toml
  src/vsmtp/vsmtp-common/Cargo.toml
  src/vsmtp/vsmtp-config/Cargo.toml
  src/vsmtp/vsmtp-delivery/Cargo.toml
  src/vsmtp/vsmtp-mail-parser/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/src/modules/actions/bcc.rs
  src/vsmtp/vsmtp-rule-engine/src/modules/actions/logging.rs
  src/vsmtp/vsmtp-rule-engine/src/modules/actions/rule_state.rs
  src/vsmtp/vsmtp-rule-engine/src/modules/actions/security.rs
  src/vsmtp/vsmtp-rule-engine/src/modules/actions/services.rs
  src/vsmtp/vsmtp-rule-engine/src/modules/actions/transports.rs
  src/vsmtp/vsmtp-rule-engine/src/modules/actions/utils.rs
  src/vsmtp/vsmtp-rule-engine/src/modules/actions/write.rs
  src/vsmtp/vsmtp-server/Cargo.toml
  src/vsmtp/vsmtp-test/Cargo.toml
Labels: P-medium, A-dependencies

#455 VSL's api folder
  README.md
  vsl-api
Labels: C-documentation

#457 Support DKIM (signer)
  Cargo.lock
  src/vsmtp/vsmtp-config/Cargo.toml
  src/vsmtp/vsmtp-config/src/builder/validate.rs
  src/vsmtp/vsmtp-config/src/builder/with.rs
  src/vsmtp/vsmtp-config/src/config.rs
  src/vsmtp/vsmtp-config/src/default.rs
  src/vsmtp/vsmtp-config/src/parser/tls_certificate.rs
  src/vsmtp/vsmtp-config/src/parser/tls_private_key.rs
  src/vsmtp/vsmtp-config/src/virtual_tls.rs
  src/vsmtp/vsmtp-dkim/Cargo.toml
  src/vsmtp/vsmtp-dkim/src/canonicalization.rs
  src/vsmtp/vsmtp-dkim/src/lib.rs
  src/vsmtp/vsmtp-dkim/src/sign.rs
  src/vsmtp/vsmtp-dkim/src/signature.rs
  src/vsmtp/vsmtp-rule-engine/src/api/auth.rhai
  src/vsmtp/vsmtp-rule-engine/src/dsl/mod.rs
  src/vsmtp/vsmtp-rule-engine/src/lib.rs
  src/vsmtp/vsmtp-rule-engine/src/modules/actions/dkim.rs
  src/vsmtp/vsmtp-rule-engine/src/tests/actions.rs
  src/vsmtp/vsmtp-test/src/tests/tls/tunneled.rs
Labels: C-enhancement, P-medium, A-vsl, A-protocol, A-config

#453 Support DKIM verfier `Authentication-Results` and signer
  .vscode/settings.json
  Cargo.lock
  src/vsmtp/vsmtp-config/Cargo.toml
  src/vsmtp/vsmtp-config/src/builder/validate.rs
  src/vsmtp/vsmtp-config/src/builder/with.rs
  src/vsmtp/vsmtp-config/src/config.rs
  src/vsmtp/vsmtp-config/src/default.rs
  src/vsmtp/vsmtp-config/src/parser/tls_certificate.rs
  src/vsmtp/vsmtp-config/src/parser/tls_private_key.rs
  src/vsmtp/vsmtp-config/src/virtual_tls.rs
  src/vsmtp/vsmtp-dkim/Cargo.toml
  src/vsmtp/vsmtp-dkim/src/canonicalization.rs
  src/vsmtp/vsmtp-dkim/src/lib.rs
  src/vsmtp/vsmtp-dkim/src/public_key.rs
  src/vsmtp/vsmtp-dkim/src/sign.rs
  src/vsmtp/vsmtp-dkim/src/signature.rs
  src/vsmtp/vsmtp-dkim/src/tests/simple2.eml
  src/vsmtp/vsmtp-dkim/src/tests/verify.rs
  src/vsmtp/vsmtp-dkim/src/verify.rs
  src/vsmtp/vsmtp-rule-engine/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/src/api/auth.rhai
  src/vsmtp/vsmtp-rule-engine/src/dsl/mod.rs
  src/vsmtp/vsmtp-rule-engine/src/lib.rs
  src/vsmtp/vsmtp-rule-engine/src/modules/actions/dkim.rs
  src/vsmtp/vsmtp-rule-engine/src/tests/actions.rs
  src/vsmtp/vsmtp-server/src/delivery/deliver.rs
  src/vsmtp/vsmtp-test/src/tests/tls/tunneled.rs
Labels: C-documentation, C-enhancement, P-medium, A-vsl, A-protocol

#463 fix: ipv6 syntax for ehlo keyword
  src/vsmtp/vsmtp-common/src/event.rs
  src/vsmtp/vsmtp-common/src/tests/event.rs
Labels: A-protocol

#460 Support `tracing`
  Cargo.lock
  Cargo.toml
  deny.toml
  examples/config/logging.toml
  fuzz/fuzz_targets/receiver.rs
  src/vsmtp/src/lib.rs
  src/vsmtp/src/main.rs
  src/vsmtp/src/tracing_subscriber.rs
  src/vsmtp/vsmtp-common/src/lib.rs
  src/vsmtp/vsmtp-common/src/queue.rs
  src/vsmtp/vsmtp-common/src/type/reply.rs
  src/vsmtp/vsmtp-config/Cargo.toml
  src/vsmtp/vsmtp-config/src/builder/validate.rs
  src/vsmtp/vsmtp-config/src/builder/wants.rs
  src/vsmtp/vsmtp-config/src/builder/with.rs
  src/vsmtp/vsmtp-config/src/config.rs
  src/vsmtp/vsmtp-config/src/default.rs
  src/vsmtp/vsmtp-config/src/lib.rs
  src/vsmtp/vsmtp-config/src/log4rs_helper.rs
  src/vsmtp/vsmtp-config/src/parser/tracing_directive.rs
  src/vsmtp/vsmtp-config/src/tests/root_example/logging.rs
  src/vsmtp/vsmtp-delivery/src/lib.rs
  src/vsmtp/vsmtp-delivery/src/transport/deliver.rs
  src/vsmtp/vsmtp-delivery/src/transport/forward.rs
  src/vsmtp/vsmtp-delivery/src/transport/maildir.rs
  src/vsmtp/vsmtp-delivery/src/transport/mbox.rs
  src/vsmtp/vsmtp-rule-engine/src/dsl/directives.rs
  src/vsmtp/vsmtp-rule-engine/src/dsl/service/cmd.rs
  src/vsmtp/vsmtp-rule-engine/src/lib.rs
  src/vsmtp/vsmtp-rule-engine/src/modules/actions/logging.rs
  src/vsmtp/vsmtp-rule-engine/src/rule_engine.rs
  src/vsmtp/vsmtp-rule-engine/src/rule_state.rs
  src/vsmtp/vsmtp-server/Cargo.toml
  src/vsmtp/vsmtp-server/benches/receiver.rs
  src/vsmtp/vsmtp-server/src/delivery/deferred.rs
  src/vsmtp/vsmtp-server/src/delivery/deliver.rs
  src/vsmtp/vsmtp-server/src/delivery/mod.rs
  src/vsmtp/vsmtp-server/src/lib.rs
  src/vsmtp/vsmtp-server/src/processing/mod.rs
  src/vsmtp/vsmtp-server/src/receiver/auth_exchange.rs
  src/vsmtp/vsmtp-server/src/receiver/connection.rs
  src/vsmtp/vsmtp-server/src/receiver/mod.rs
  src/vsmtp/vsmtp-server/src/receiver/on_mail.rs
  src/vsmtp/vsmtp-server/src/receiver/transaction.rs
  src/vsmtp/vsmtp-server/src/runtime.rs
  src/vsmtp/vsmtp-server/src/server.rs
  src/vsmtp/vsmtp-test/src/receiver.rs
  src/vsmtp/vsmtp-test/src/tests/auth/basic.rs
  src/vsmtp/vsmtp-test/src/tests/clair.rs
  src/vsmtp/vsmtp-test/src/tests/examples/doe_family.rs
  src/vsmtp/vsmtp-test/src/tests/rset.rs
  src/vsmtp/vsmtp-test/src/tests/tls/mod.rs
  src/vsmtp/vsmtp-test/src/tests/utf8.rs
Labels: C-enhancement, P-medium

#462 Support integration with `tokio-console`
  Cargo.lock
  Cargo.toml
  src/vsmtp/src/tracing_subscriber.rs
Labels: C-enhancement, P-medium, A-delivery, A-net, A-perf
