Repository viridIT/vSMTP, pull requests merged in 2022-09, with the labels that each got.

#536 Use latest `rsasl` version
  Cargo.lock
  Cargo.toml
  benchmarks/stress/main.vsl
  fuzz/fuzz_targets/receiver.rs
  src/vqueue/Cargo.toml
  src/vsmtp/vsmtp-auth/Cargo.toml
  src/vsmtp/vsmtp-common/Cargo.toml
  src/vsmtp/vsmtp-common/src/auth/credentials.rs
  src/vsmtp/vsmtp-common/src/auth/mechanism.rs
  src/vsmtp/vsmtp-common/src/lib.rs
  src/vsmtp/vsmtp-common/src/state.rs
  src/vsmtp/vsmtp-config/Cargo.toml
  src/vsmtp/vsmtp-delivery/Cargo.toml
  src/vsmtp/vsmtp-docs/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/api/auth.rhai
  src/vsmtp/vsmtp-rule-engine/api/security.rhai
  src/vsmtp/vsmtp-rule-engine/src/api/mail_context.rs
  src/vsmtp/vsmtp-rule-engine/src/api/message.rs
  src/vsmtp/vsmtp-rule-engine/src/dsl/directives.rs
  src/vsmtp/vsmtp-rule-engine/src/lib.rs
  src/vsmtp/vsmtp-rule-engine/src/rule_engine.rs
  src/vsmtp/vsmtp-rule-engine/src/tests/actions.rs
  src/vsmtp/vsmtp-rule-engine/src/tests/context/mod.rs
  src/vsmtp/vsmtp-rule-engine/src/tests/engine/mod.rs
  src/vsmtp/vsmtp-rule-engine/src/tests/message/mod.rs
  src/vsmtp/vsmtp-rule-engine/src/tests/rules.rs
  src/vsmtp/vsmtp-rule-engine/src/tests/types/mod.rs
  src/vsmtp/vsmtp-server/Cargo.toml
  src/vsmtp/vsmtp-server/src/auth.rs
  src/vsmtp/vsmtp-server/src/delivery/deliver.rs
  src/vsmtp/vsmtp-server/src/lib.rs
  src/vsmtp/vsmtp-server/src/processing/mod.rs
  src/vsmtp/vsmtp-server/src/receiver/auth_exchange.rs
  src/vsmtp/vsmtp-server/src/receiver/mod.rs
  src/vsmtp/vsmtp-server/src/receiver/transaction.rs
  src/vsmtp/vsmtp-server/src/rsasl_callback.rs
  src/vsmtp/vsmtp-server/src/server.rs
  src/vsmtp/vsmtp-test/Cargo.toml
  src/vsmtp/vsmtp-test/src/receiver.rs
  src/vsmtp/vsmtp-test/src/tests/auth.vsl
  src/vsmtp/vsmtp-test/src/tests/auth/basic.rs
  src/vsmtp/vsmtp-test/src/tests/rules/codes/mod.rs
  src/vsmtp/vsmtp-test/src/tests/tls/cipher_suite.rs
  src/vsmtp/vsmtp-test/src/tests/tls/mod.rs
  src/vsmtp/vsmtp-test/src/tests/tls/tunneled.rs
  src/vsmtp/vsmtp-test/src/tests/tls/tunneled_with_auth.rs
  src/vsmtp/vsmtp-test/src/vsl.rs
Labels: C-enhancement, A-protocol, A-security, A-dependencies

#548 MySQL installation & database setup
  examples/greylist/README.md
  examples/greylist/mysql/README.md
  examples/greylist/mysql/greylist.sql
  examples/greylist/mysql/greylist.vsl
Labels: C-documentation

#549 Document vsl api for DKIM/DMARC
  .github/workflows/ci.yaml
  Cargo.lock
  Cargo.toml
  examples/greylist/csv_greylist.vsl
  examples/greylist/main.vsl
  src/vsmtp/vsmtp-auth/src/dkim/canonicalization.rs
  src/vsmtp/vsmtp-auth/src/dkim/mod.rs
  src/vsmtp/vsmtp-auth/src/dkim/public_key.rs
  src/vsmtp/vsmtp-auth/src/dkim/sign.rs
  src/vsmtp/vsmtp-auth/src/dkim/signature.rs
  src/vsmtp/vsmtp-auth/src/dkim/tests/mail_1.eml
  src/vsmtp/vsmtp-auth/src/dkim/tests/mail_2.eml
  src/vsmtp/vsmtp-auth/src/dkim/tests/verify.rs
  src/vsmtp/vsmtp-auth/src/dkim/verify.rs
  src/vsmtp/vsmtp-auth/src/dmarc/record.rs
  src/vsmtp/vsmtp-auth/src/lib.rs
  src/vsmtp/vsmtp-docs/Cargo.lock
  src/vsmtp/vsmtp-docs/Cargo.toml
  src/vsmtp/vsmtp-docs/README.md
  src/vsmtp/vsmtp-docs/src/main.rs
  src/vsmtp/vsmtp-rule-engine/api/security.rhai
  src/vsmtp/vsmtp-rule-engine/src/api/dkim.rs
  src/vsmtp/vsmtp-rule-engine/src/api/dmarc.rs
  src/vsmtp/vsmtp-test/Cargo.toml
Labels: C-documentation, C-enhancement, P-medium

#555 fix<ci>: set fixed nightly version
  .github/workflows/ci.yaml
Labels: P-critical, A-ci

#553 Improve doc and test for DKIM / DMARC
  CHANGELOG.md
  src/vsmtp/vsmtp-auth/Cargo.toml
  src/vsmtp/vsmtp-auth/src/dkim/algorithm.rs
  src/vsmtp/vsmtp-auth/src/dkim/canonicalization.rs
  src/vsmtp/vsmtp-auth/src/dkim/mod.rs
  src/vsmtp/vsmtp-auth/src/dkim/public_key.rs
  src/vsmtp/vsmtp-auth/src/dkim/signature.rs
  src/vsmtp/vsmtp-auth/src/dkim/verify.rs
  src/vsmtp/vsmtp-auth/src/dmarc/record.rs
  src/vsmtp/vsmtp-auth/src/lib.rs
  src/vsmtp/vsmtp-common/src/auth/mechanism.rs
  src/vsmtp/vsmtp-common/src/libc_abstraction.rs
  src/vsmtp/vsmtp-common/src/state.rs
  src/vsmtp/vsmtp-common/src/status.rs
  src/vsmtp/vsmtp-common/src/tests/libc_abstraction.rs
  src/vsmtp/vsmtp-config/src/builder/with.rs
  src/vsmtp/vsmtp-config/src/lib.rs
  src/vsmtp/vsmtp-config/src/tests/root_example/secured.rs
  src/vsmtp/vsmtp-rule-engine/src/api/mail_context.rs
  src/vsmtp/vsmtp-rule-engine/src/dsl/directives.rs
  src/vsmtp/vsmtp-rule-engine/src/error.rs
  src/vsmtp/vsmtp-rule-engine/src/rule_engine.rs
  src/vsmtp/vsmtp-rule-engine/src/tests/actions.rs
  src/vsmtp/vsmtp-rule-engine/src/tests/context/mod.rs
  src/vsmtp/vsmtp-rule-engine/src/tests/engine/mod.rs
  src/vsmtp/vsmtp-rule-engine/src/tests/message/mod.rs
  src/vsmtp/vsmtp-rule-engine/src/tests/rules.rs
  src/vsmtp/vsmtp-rule-engine/src/tests/types/mod.rs
  src/vsmtp/vsmtp-server/src/delivery/deliver.rs
  src/vsmtp/vsmtp-server/src/lib.rs
  src/vsmtp/vsmtp-server/src/processing/mod.rs
  src/vsmtp/vsmtp-server/src/receiver/connection.rs
  src/vsmtp/vsmtp-server/src/receiver/mod.rs
  src/vsmtp/vsmtp-server/src/receiver/on_mail.rs
  src/vsmtp/vsmtp-server/src/receiver/rsasl_callback.rs
  src/vsmtp/vsmtp-server/src/receiver/rsasl_exchange.rs
  src/vsmtp/vsmtp-server/src/receiver/transaction.rs
  src/vsmtp/vsmtp-test/src/tests/auth/mod.rs
  src/vsmtp/vsmtp-test/src/vsl.rs
Labels: C-documentation, A-protocol, A-security, A-test

#566 Greylist sender domain
  examples/greylist/main.vsl
  examples/greylist/mysql/greylist.vsl
Labels: C-documentation

#565 Fix/log level filter
  src/vsmtp/src/tracing_subscriber.rs
  src/vsmtp/vsmtp-config/src/config.rs
Labels: P-high, A-log

#569 Pre-release v1.3.0-rc.2
  .github/workflows/pre-release.yaml
  .github/workflows/release.yml
  Cargo.lock
  Cargo.toml
  examples/config/minimal.toml
  examples/greylist/main.vsl
  examples/greylist/mysql/greylist.vsl
  src/vqueue/Cargo.toml
  src/vsmtp/src/tracing_subscriber.rs
  src/vsmtp/vsmtp-config/src/config.rs
  src/vsmtp/vsmtp-rule-engine/src/api/types.rs
Labels: B-candidate

#571 Greylist deny code
  README.md
  examples/greylist/main.vsl
  examples/greylist/mysql/greylist.vsl
  src/vsmtp/vsmtp-rule-engine/api/codes.rhai
  src/vsmtp/vsmtp-test/src/tests/examples/greylist.rs
Labels: C-documentation, A-vsl

#573 1.3 Changelog
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  examples/config/minimal.toml
  src/vqueue/Cargo.toml
  src/vsmtp/vsmtp-auth/Cargo.toml
  src/vsmtp/vsmtp-common/Cargo.toml
  src/vsmtp/vsmtp-config/Cargo.toml
  src/vsmtp/vsmtp-delivery/Cargo.toml
  src/vsmtp/vsmtp-docs/Cargo.toml
  src/vsmtp/vsmtp-mail-parser/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/Cargo.toml
  src/vsmtp/vsmtp-server/Cargo.toml
  src/vsmtp/vsmtp-test/Cargo.toml
  tools/install/deb/changelog
Labels: C-documentation

#574 v1.3.0
  CHANGELOG.md
  README.md
  examples/config/minimal.toml
  examples/greylist/main.vsl
  examples/greylist/mysql/greylist.vsl
  src/vsmtp/vsmtp-rule-engine/api/codes.rhai
  src/vsmtp/vsmtp-test/src/tests/examples/greylist.rs
  tools/install/deb/changelog
Labels: B-release

#575 Tweak CI
  .github/workflows/benchmark.yaml
  .github/workflows/ci.yaml
  .github/workflows/fuzzer.yaml
  .github/workflows/post-release.yaml
  .github/workflows/pre-release.yaml
  .github/workflows/release.yml
  .vscode/settings.json
  examples/config/minimal.toml
  src/vsmtp/vsmtp-auth/src/dkim/mod.rs
  src/vsmtp/vsmtp-common/src/status.rs
  src/vsmtp/vsmtp-config/src/default.rs
  src/vsmtp/vsmtp-config/src/tests/mod.rs
  src/vsmtp/vsmtp-config/src/tests/root_example/minimal.rs
Labels: P-medium, A-ci

#579 --stdout flag
  CHANGELOG.md
  src/vsmtp/src/args.rs
  src/vsmtp/src/tracing_subscriber.rs
  src/vsmtp/vsmtp-rule-engine/src/rule_state.rs
  tools/install/deb/changelog
Labels: C-enhancement, A-log

#580 Message size limit
  CHANGELOG.md
  src/vsmtp/vsmtp-common/src/event.rs
  src/vsmtp/vsmtp-common/src/types/code_id.rs
  src/vsmtp/vsmtp-config/src/builder/validate.rs
  src/vsmtp/vsmtp-config/src/builder/wants.rs
  src/vsmtp/vsmtp-config/src/builder/with.rs
  src/vsmtp/vsmtp-config/src/config.rs
  src/vsmtp/vsmtp-config/src/default.rs
  src/vsmtp/vsmtp-server/src/receiver/transaction.rs
  src/vsmtp/vsmtp-test/src/tests/message_max_size.rs
  src/vsmtp/vsmtp-test/src/tests/mod.rs
  tools/install/deb/changelog
Labels: C-enhancement, A-protocol

#585 Further information for `--version` flag
  CHANGELOG.md
  Cargo.toml
  build.rs
  src/vqueue/Cargo.toml
  src/vqueue/build.rs
  src/vqueue/src/args.rs
  src/vqueue/src/main.rs
  src/vsmtp/src/args.rs
  src/vsmtp/src/main.rs
  tools/install/deb/changelog
Labels: P-low, A-config

#586 Update the badge and the logos in the README.md
  README.md
Labels: C-documentation, P-medium

#588 Chore/faster ci
  .github/workflows/ci.yaml
Labels: A-ci, A-test

#587 Patch: Log contents
  CHANGELOG.md
  Cargo.lock
  src/vqueue/Cargo.toml
  src/vqueue/src/api.rs
  src/vqueue/src/implementation/fs.rs
  src/vsmtp/src/main.rs
  src/vsmtp/src/tracing_subscriber.rs
  src/vsmtp/vsmtp-auth/src/dkim/signature.rs
  src/vsmtp/vsmtp-auth/src/dmarc/record.rs
  src/vsmtp/vsmtp-common/src/event.rs
  src/vsmtp/vsmtp-common/src/queue.rs
  src/vsmtp/vsmtp-common/src/types/reply.rs
  src/vsmtp/vsmtp-config/src/config.rs
  src/vsmtp/vsmtp-config/src/default.rs
  src/vsmtp/vsmtp-config/src/rustls_helper.rs
  src/vsmtp/vsmtp-delivery/src/transport/deliver.rs
  src/vsmtp/vsmtp-delivery/src/transport/forward.rs
  src/vsmtp/vsmtp-delivery/src/transport/maildir.rs
  src/vsmtp/vsmtp-delivery/src/transport/mbox.rs
  src/vsmtp/vsmtp-mail-parser/src/parser.rs
  src/vsmtp/vsmtp-rule-engine/src/api/logging.rs
  src/vsmtp/vsmtp-rule-engine/src/dsl/directives.rs
  src/vsmtp/vsmtp-rule-engine/src/dsl/object/mod.rs
  src/vsmtp/vsmtp-rule-engine/src/dsl/service/cmd/mod.rs
  src/vsmtp/vsmtp-rule-engine/src/rule_engine.rs
  src/vsmtp/vsmtp-server/src/delivery/deferred.rs
  src/vsmtp/vsmtp-server/src/delivery/deliver.rs
  src/vsmtp/vsmtp-server/src/delivery/mod.rs
  src/vsmtp/vsmtp-server/src/processing/mod.rs
  src/vsmtp/vsmtp-server/src/receiver/connection.rs
  src/vsmtp/vsmtp-server/src/receiver/mod.rs
  src/vsmtp/vsmtp-server/src/receiver/on_mail.rs
  src/vsmtp/vsmtp-server/src/receiver/rsasl_exchange.rs
  src/vsmtp/vsmtp-server/src/receiver/transaction.rs
  src/vsmtp/vsmtp-server/src/runtime.rs
  src/vsmtp/vsmtp-server/src/server.rs
  tools/install/deb/changelog
Labels: A-config, A-log

#601 bump: MSRV to 1.62.1
  .github/workflows/ci.yaml
  Cargo.toml
  README.md
  benchmarks/stress/Cargo.toml
  src/vqueue/Cargo.toml
  src/vsmtp/vsmtp-auth/Cargo.toml
  src/vsmtp/vsmtp-common/Cargo.toml
  src/vsmtp/vsmtp-config/Cargo.toml
  src/vsmtp/vsmtp-delivery/Cargo.toml
  src/vsmtp/vsmtp-docs/Cargo.toml
  src/vsmtp/vsmtp-mail-parser/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/Cargo.toml
  src/vsmtp/vsmtp-server/Cargo.toml
  src/vsmtp/vsmtp-server/src/receiver/io.rs
  src/vsmtp/vsmtp-test/Cargo.toml
Labels: P-medium, A-dependencies

#603 Lintian in CI
  .github/workflows/pre-release.yaml
Labels: C-bug, A-ci

#621 Remove `static_registry` feature of rsasl
  Cargo.lock
  src/vsmtp/vsmtp-server/Cargo.toml
  src/vsmtp/vsmtp-test/Cargo.toml
Labels: A-dependencies

#624 Rhai debugging
  src/vsmtp/vsmtp-rule-engine/src/rule_engine.rs
  src/vsmtp/vsmtp-rule-engine/src/rule_state.rs
Labels: A-vsl

#600 Support ed25519 key for DKIM
  Cargo.lock
  examples/config/secured.toml
  src/vqueue/src/implementation/fs.rs
  src/vsmtp/vsmtp-auth/Cargo.toml
  src/vsmtp/vsmtp-auth/src/dkim/algorithm.rs
  src/vsmtp/vsmtp-auth/src/dkim/canonicalization.rs
  src/vsmtp/vsmtp-auth/src/dkim/mod.rs
  src/vsmtp/vsmtp-auth/src/dkim/private_key.rs
  src/vsmtp/vsmtp-auth/src/dkim/public_key.rs
  src/vsmtp/vsmtp-auth/src/dkim/record.rs
  src/vsmtp/vsmtp-auth/src/dkim/signature.rs
  src/vsmtp/vsmtp-auth/src/dkim/tests/canonicalization.rs
  src/vsmtp/vsmtp-auth/src/dkim/tests/parse/public_key.rs
  src/vsmtp/vsmtp-auth/src/dkim/tests/parse/signature_header.rs
  src/vsmtp/vsmtp-auth/src/dkim/tests/sign_verify.rs
  src/vsmtp/vsmtp-auth/src/dkim/verify.rs
  src/vsmtp/vsmtp-auth/src/dmarc/record.rs
  src/vsmtp/vsmtp-auth/src/lib.rs
  src/vsmtp/vsmtp-common/src/mail_context.rs
  src/vsmtp/vsmtp-common/src/queue.rs
  src/vsmtp/vsmtp-config/Cargo.toml
  src/vsmtp/vsmtp-config/src/builder/validate.rs
  src/vsmtp/vsmtp-config/src/builder/wants.rs
  src/vsmtp/vsmtp-config/src/builder/with.rs
  src/vsmtp/vsmtp-config/src/config.rs
  src/vsmtp/vsmtp-config/src/default.rs
  src/vsmtp/vsmtp-config/src/lib.rs
  src/vsmtp/vsmtp-config/src/rustls_helper.rs
  src/vsmtp/vsmtp-config/src/tests/root_example/logging.rs
  src/vsmtp/vsmtp-config/src/tests/root_example/tls.rs
  src/vsmtp/vsmtp-config/src/virtual_tls.rs
  src/vsmtp/vsmtp-rule-engine/src/api/dkim.rs
  src/vsmtp/vsmtp-rule-engine/src/tests/types/mod.rs
  src/vsmtp/vsmtp-server/benches/receiver.rs
  src/vsmtp/vsmtp-test/Cargo.toml
  src/vsmtp/vsmtp-test/src/lib.rs
  src/vsmtp/vsmtp-test/src/receiver.rs
  src/vsmtp/vsmtp-test/src/tests/auth/basic.rs
  src/vsmtp/vsmtp-test/src/tests/clair.rs
  src/vsmtp/vsmtp-test/src/tests/examples/aliases.rs
  src/vsmtp/vsmtp-test/src/tests/examples/anti_relaying.rs
  src/vsmtp/vsmtp-test/src/tests/examples/dnsbl.rs
  src/vsmtp/vsmtp-test/src/tests/examples/family.rs
  src/vsmtp/vsmtp-test/src/tests/examples/greylist.rs
  src/vsmtp/vsmtp-test/src/tests/examples/message.rs
  src/vsmtp/vsmtp-test/src/tests/examples/services.rs
  src/vsmtp/vsmtp-test/src/tests/message_max_size.rs
  src/vsmtp/vsmtp-test/src/tests/rules/codes/mod.rs
  src/vsmtp/vsmtp-test/src/tests/tls/cipher_suite.rs
  src/vsmtp/vsmtp-test/src/tests/tls/mod.rs
  src/vsmtp/vsmtp-test/src/tests/tls/starttls.rs
  src/vsmtp/vsmtp-test/src/tests/tls/tunneled.rs
  src/vsmtp/vsmtp-test/src/tests/tls/tunneled_with_auth.rs
  src/vsmtp/vsmtp-test/src/tests/vqueue/mod.rs
  src/vsmtp/vsmtp-test/src/vsl.rs
Labels: C-enhancement, P-medium, A-protocol, A-config, A-security

#622 refact: unify & clean MailParser api
  Cargo.lock
  fuzz/fuzz_targets/mime_parser.rs
  src/vsmtp/vsmtp-common/src/status.rs
  src/vsmtp/vsmtp-mail-parser/Cargo.toml
  src/vsmtp/vsmtp-mail-parser/src/helpers.rs
  src/vsmtp/vsmtp-mail-parser/src/implementation/basic_parser.rs
  src/vsmtp/vsmtp-mail-parser/src/implementation/mail_mime_parser.rs
  src/vsmtp/vsmtp-mail-parser/src/lib.rs
  src/vsmtp/vsmtp-mail-parser/src/message/message_body.rs
  src/vsmtp/vsmtp-mail-parser/src/message/raw_body.rs
  src/vsmtp/vsmtp-mail-parser/src/tests/mime_parser/allen_p__discussion_threads__1.rs
  src/vsmtp/vsmtp-mail-parser/src/tests/mime_parser/mime1.rs
  src/vsmtp/vsmtp-mail-parser/src/tests/mime_parser/rfc2049/a.rs
  src/vsmtp/vsmtp-mail-parser/src/tests/mime_parser/rfc5322/a_1_1.rs
  src/vsmtp/vsmtp-mail-parser/src/tests/mime_parser/rfc5322/a_1_2.rs
  src/vsmtp/vsmtp-mail-parser/src/tests/mime_parser/rfc5322/a_1_3.rs
  src/vsmtp/vsmtp-mail-parser/src/tests/mime_parser/rfc5322/a_2.rs
  src/vsmtp/vsmtp-mail-parser/src/tests/mime_parser/rfc5322/a_3.rs
  src/vsmtp/vsmtp-mail-parser/src/tests/mime_parser/rfc5322/a_4.rs
  src/vsmtp/vsmtp-mail-parser/src/tests/mime_parser/rfc5322/a_5.rs
  src/vsmtp/vsmtp-mail-parser/src/tests/mod.rs
  src/vsmtp/vsmtp-mail-parser/src/traits/error.rs
  src/vsmtp/vsmtp-mail-parser/src/traits/mail_parser.rs
  src/vsmtp/vsmtp-rule-engine/src/api/rule_state.rs
  src/vsmtp/vsmtp-server/src/receiver/mod.rs
  src/vsmtp/vsmtp-server/src/receiver/transaction.rs
Labels: P-medium

#628 Rhai generic error macro
  src/vsmtp/vsmtp-rule-engine/src/error.rs
Labels: C-enhancement, A-vsl

#639 Update post release CI
  .github/workflows/post-release.yaml
Labels: A-ci
