Repository viridIT/vSMTP, pull requests merged in 2022-08, with the labels that each got.

#473 Lookup & reverse lookup
  .vscode/settings.json
  examples/vsl/actions/utils.vsl
  src/vsmtp/vsmtp-rule-engine/src/api/sys-api.rhai
  src/vsmtp/vsmtp-rule-engine/src/modules/actions/utils.rs
  src/vsmtp/vsmtp-rule-engine/src/tests/actions.rs
Labels: A-vsl

#475 Support for `syslog`
  Cargo.lock
  Cargo.toml
  src/vsmtp/src/tracing_subscriber.rs
Labels: C-enhancement, A-log

#486 Doctest for vsl's api
  .vscode/settings.json
  Cargo.lock
  src/vsmtp/vsmtp-auth/src/dkim/public_key.rs
  src/vsmtp/vsmtp-common/Cargo.toml
  src/vsmtp/vsmtp-common/src/event.rs
  src/vsmtp/vsmtp-common/src/type/address.rs
  src/vsmtp/vsmtp-config/src/config.rs
  src/vsmtp/vsmtp-rule-engine/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/src/api/logging.rs
  src/vsmtp/vsmtp-rule-engine/src/api/mail_context.rs
  src/vsmtp/vsmtp-rule-engine/src/api/message_parsed.rs
  src/vsmtp/vsmtp-rule-engine/src/dsl/object/mod.rs
  src/vsmtp/vsmtp-rule-engine/src/lib.rs
  src/vsmtp/vsmtp-rule-engine/src/rule_engine.rs
  src/vsmtp/vsmtp-rule-engine/src/rule_state.rs
  src/vsmtp/vsmtp-server/src/delivery/deliver.rs
  src/vsmtp/vsmtp-server/src/processing/mod.rs
  src/vsmtp/vsmtp-test/src/lib.rs
  src/vsmtp/vsmtp-test/src/tests/clair.rs
  src/vsmtp/vsmtp-test/src/vsl.rs
Labels: C-documentation, P-high, A-test

#504 Update for rustc 1.63 & clean receiver side
  .vscode/extensions.json
  Cargo.lock
  examples/config/secured.toml
  src/vqueue/src/args.rs
  src/vsmtp/vsmtp-common/Cargo.toml
  src/vsmtp/vsmtp-common/src/auth/mechanism.rs
  src/vsmtp/vsmtp-common/src/either.rs
  src/vsmtp/vsmtp-common/src/envelop.rs
  src/vsmtp/vsmtp-common/src/event.rs
  src/vsmtp/vsmtp-common/src/lib.rs
  src/vsmtp/vsmtp-common/src/message/mail.rs
  src/vsmtp/vsmtp-common/src/message/message_body.rs
  src/vsmtp/vsmtp-common/src/state.rs
  src/vsmtp/vsmtp-common/src/traits/mail_parser.rs
  src/vsmtp/vsmtp-common/src/types/address.rs
  src/vsmtp/vsmtp-common/src/types/code_id.rs
  src/vsmtp/vsmtp-common/src/types/reply.rs
  src/vsmtp/vsmtp-common/src/types/reply_code.rs
  src/vsmtp/vsmtp-config/src/builder/with.rs
  src/vsmtp/vsmtp-config/src/config.rs
  src/vsmtp/vsmtp-config/src/tests/root_example/secured.rs
  src/vsmtp/vsmtp-mail-parser/src/parser.rs
  src/vsmtp/vsmtp-rule-engine/src/api/mail_context.rs
  src/vsmtp/vsmtp-rule-engine/src/dsl/object/mod.rs
  src/vsmtp/vsmtp-rule-engine/src/rule_state.rs
  src/vsmtp/vsmtp-rule-engine/src/tests/context/mod.rs
  src/vsmtp/vsmtp-server/src/auth.rs
  src/vsmtp/vsmtp-server/src/receiver/connection.rs
  src/vsmtp/vsmtp-server/src/receiver/io.rs
  src/vsmtp/vsmtp-server/src/receiver/mod.rs
  src/vsmtp/vsmtp-server/src/receiver/transaction.rs
  src/vsmtp/vsmtp-test/src/tests/auth/basic.rs
  src/vsmtp/vsmtp-test/src/tests/clair.rs
  src/vsmtp/vsmtp-test/src/tests/examples/anti_relaying.rs
  src/vsmtp/vsmtp-test/src/tests/examples/dnsbl.rs
  src/vsmtp/vsmtp-test/src/tests/examples/family.rs
  src/vsmtp/vsmtp-test/src/tests/rset.rs
  src/vsmtp/vsmtp-test/src/tests/rules/codes/mod.rs
  src/vsmtp/vsmtp-test/src/tests/tls/starttls.rs
  src/vsmtp/vsmtp-test/src/tests/tls/tunneled.rs
Labels: C-enhancement, P-medium, A-protocol

#503 VSL system api
  .vscode/settings.json
  src/vsmtp/vsmtp-rule-engine/api/auth.rhai
  src/vsmtp/vsmtp-rule-engine/api/connection.rhai
  src/vsmtp/vsmtp-rule-engine/api/delivery.rhai
  src/vsmtp/vsmtp-rule-engine/api/envelop.rhai
  src/vsmtp/vsmtp-rule-engine/api/internal.rhai
  src/vsmtp/vsmtp-rule-engine/api/message.rhai
  src/vsmtp/vsmtp-rule-engine/api/security.rhai
  src/vsmtp/vsmtp-rule-engine/api/services.rhai
  src/vsmtp/vsmtp-rule-engine/api/status.rhai
  src/vsmtp/vsmtp-rule-engine/api/sys-api.rhai
  src/vsmtp/vsmtp-rule-engine/api/transaction.rhai
  src/vsmtp/vsmtp-rule-engine/api/utils.rhai
  src/vsmtp/vsmtp-rule-engine/src/api/spf.rs
  src/vsmtp/vsmtp-rule-engine/src/rule_engine.rs
Labels: A-vsl

#518 VSL Getters
  README.md
  examples/message/main.vsl
  src/vsmtp/vsmtp-rule-engine/api/message.rhai
  src/vsmtp/vsmtp-rule-engine/api/services.rhai
  src/vsmtp/vsmtp-rule-engine/src/tests/types/service/main.vsl
Labels: C-documentation

#521 Fix release CI
  .github/workflows/post-release.yaml
Labels: A-ci

#520 Docs
  src/vsmtp/vsmtp-rule-engine/api/message.rhai
Labels: C-documentation

#509 Configuration of `syslog`
  Cargo.lock
  src/vsmtp/src/tracing_subscriber.rs
  src/vsmtp/vsmtp-config/Cargo.toml
  src/vsmtp/vsmtp-config/src/builder/validate.rs
  src/vsmtp/vsmtp-config/src/config.rs
  src/vsmtp/vsmtp-config/src/default.rs
  src/vsmtp/vsmtp-rule-engine/src/api/dmarc.rs
  src/vsmtp/vsmtp-rule-engine/src/api/utils.rs
Labels: C-enhancement, P-medium, A-config, A-log

#482 Support journactl
  Cargo.lock
  Cargo.toml
  src/vsmtp/src/tracing_subscriber.rs
  src/vsmtp/vsmtp-auth/src/lib.rs
  src/vsmtp/vsmtp-common/src/lib.rs
  src/vsmtp/vsmtp-common/src/libc_abstraction.rs
  src/vsmtp/vsmtp-config/src/builder/validate.rs
  src/vsmtp/vsmtp-config/src/config.rs
  src/vsmtp/vsmtp-config/src/default.rs
  src/vsmtp/vsmtp-docs/src/main.rs
  src/vsmtp/vsmtp-server/src/auth.rs
  src/vsmtp/vsmtp-server/src/lib.rs
Labels: C-enhancement, P-medium, A-log

#529 Fix ci release
  .github/workflows/post-release.yaml
  Cargo.toml
  release.toml
Labels: C-enhancement, P-medium, A-ci

#530 fix: allow IPV6 (case insensitive) for ehlo command
  src/vsmtp/vsmtp-common/src/event.rs
  src/vsmtp/vsmtp-common/src/tests/event.rs
Labels: C-enhancement, P-medium, A-protocol

#535 Milestones
  README.md
  ROADMAP.md
Labels: C-documentation

#524 New VSL functions
  src/vsmtp/vsmtp-mail-parser/src/message/mail.rs
  src/vsmtp/vsmtp-mail-parser/src/message/message_body.rs
  src/vsmtp/vsmtp-mail-parser/src/message/raw_body.rs
  src/vsmtp/vsmtp-rule-engine/api/message.rhai
  src/vsmtp/vsmtp-rule-engine/api/security.rhai
  src/vsmtp/vsmtp-rule-engine/api/types.rhai
  src/vsmtp/vsmtp-rule-engine/src/api/message.rs
  src/vsmtp/vsmtp-rule-engine/src/api/types.rs
  src/vsmtp/vsmtp-rule-engine/src/dsl/object/mod.rs
  src/vsmtp/vsmtp-rule-engine/src/rule_engine.rs
  src/vsmtp/vsmtp-rule-engine/src/tests/message/mutate_header/main.vsl
  src/vsmtp/vsmtp-rule-engine/src/tests/types/objects/functions.vsl
  src/vsmtp/vsmtp-rule-engine/src/tests/types/objects/main.vsl
Labels: C-enhancement, A-vsl

#545 Auto doc style update
  benchmarks/stress/main.vsl
  examples/antivirus/main.vsl
  examples/message/main.vsl
  src/vsmtp/vsmtp-docs/Cargo.lock
  src/vsmtp/vsmtp-docs/src/main.rs
  src/vsmtp/vsmtp-rule-engine/api/auth.rhai
  src/vsmtp/vsmtp-rule-engine/api/codes.rhai
  src/vsmtp/vsmtp-rule-engine/api/connection.rhai
  src/vsmtp/vsmtp-rule-engine/api/default_rules.rhai
  src/vsmtp/vsmtp-rule-engine/api/delivery.rhai
  src/vsmtp/vsmtp-rule-engine/api/envelop.rhai
  src/vsmtp/vsmtp-rule-engine/api/getters.rhai
  src/vsmtp/vsmtp-rule-engine/api/internal.rhai
  src/vsmtp/vsmtp-rule-engine/api/message.rhai
  src/vsmtp/vsmtp-rule-engine/api/networks.rhai
  src/vsmtp/vsmtp-rule-engine/api/security.rhai
  src/vsmtp/vsmtp-rule-engine/api/services.rhai
  src/vsmtp/vsmtp-rule-engine/api/status.rhai
  src/vsmtp/vsmtp-rule-engine/api/transaction.rhai
  src/vsmtp/vsmtp-rule-engine/api/utils.rhai
  src/vsmtp/vsmtp-rule-engine/src/tests/actions/utils.vsl
  src/vsmtp/vsmtp-rule-engine/src/tests/engine/error_handling/errors.vsl
  src/vsmtp/vsmtp-rule-engine/src/tests/engine/error_handling/main.vsl
  src/vsmtp/vsmtp-rule-engine/src/tests/message/bcc/bcc.vsl
  src/vsmtp/vsmtp-rule-engine/src/tests/message/main.vsl
  src/vsmtp/vsmtp-rule-engine/src/tests/rules/connect.vsl
  src/vsmtp/vsmtp-rule-engine/src/tests/rules/helo.vsl
  src/vsmtp/vsmtp-rule-engine/src/tests/rules/mail.vsl
  src/vsmtp/vsmtp-rule-engine/src/tests/types/ip/main.vsl
  src/vsmtp/vsmtp-test/src/tests/auth.vsl
  src/vsmtp/vsmtp-test/src/tests/rules/codes/custom_codes_accept.vsl
  src/vsmtp/vsmtp-test/src/tests/rules/codes/custom_codes_deny.vsl
  src/vsmtp/vsmtp-test/src/tests/rules/codes/custom_codes_info.vsl
  src/vsmtp/vsmtp-test/src/tests/rules/quarantine/main.vsl
  src/vsmtp/vsmtp-test/src/vsl/sni.vsl
Labels: C-documentation

#507 Databases support
  .vscode/settings.json
  Cargo.lock
  Cargo.toml
  examples/alias/README.md
  examples/alias/aliases.vsl
  examples/alias/main.vsl
  examples/alias/vsmtp.toml
  examples/greylist/csv_greylist.vsl
  examples/greylist/main.vsl
  examples/greylist/mysql_greylist.vsl
  src/vsmtp/vsmtp-rule-engine/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/api/services.rhai
  src/vsmtp/vsmtp-rule-engine/src/api/services.rs
  src/vsmtp/vsmtp-rule-engine/src/dsl/service/databases/csv.rs
  src/vsmtp/vsmtp-rule-engine/src/dsl/service/databases/mod.rs
  src/vsmtp/vsmtp-rule-engine/src/dsl/service/databases/mysql.rs
  src/vsmtp/vsmtp-rule-engine/src/dsl/service/mod.rs
  src/vsmtp/vsmtp-rule-engine/src/dsl/service/parsing.rs
  src/vsmtp/vsmtp-rule-engine/src/dsl/service/smtp.rs
  src/vsmtp/vsmtp-test/src/tests/examples/aliases.rs
  src/vsmtp/vsmtp-test/src/tests/examples/mod.rs
Labels: C-enhancement, A-vsl, A-dependencies
