Repository viridIT/vSMTP, pull requests merged in 2022-06, with the labels that each got.

#342 Feat/mail folding
  Cargo.lock
  src/vqueue/src/command/msg_command/show.rs
  src/vsmtp/vsmtp-common/Cargo.toml
  src/vsmtp/vsmtp-common/src/lib.rs
  src/vsmtp/vsmtp-common/src/mail_context.rs
  src/vsmtp/vsmtp-common/src/message/mail.rs
  src/vsmtp/vsmtp-common/src/message/mime_type.rs
  src/vsmtp/vsmtp-delivery/Cargo.toml
  src/vsmtp/vsmtp-delivery/src/transport/deliver.rs
  src/vsmtp/vsmtp-mail-parser/src/tests/mime_parser/rfc2049/a.rs
  src/vsmtp/vsmtp-mail-parser/src/tests/mime_parser/rfc5322/a_1_1.rs
  src/vsmtp/vsmtp-mail-parser/src/tests/mime_parser/rfc5322/a_1_2.rs
  src/vsmtp/vsmtp-mail-parser/src/tests/mime_parser/rfc5322/a_1_3.rs
  src/vsmtp/vsmtp-mail-parser/src/tests/mime_parser/rfc5322/a_2.rs
  src/vsmtp/vsmtp-mail-parser/src/tests/mime_parser/rfc5322/a_3.rs
  src/vsmtp/vsmtp-mail-parser/src/tests/mime_parser/rfc5322/a_4.rs
  src/vsmtp/vsmtp-mail-parser/src/tests/mime_parser/rfc5322/a_5.rs
  src/vsmtp/vsmtp-rule-engine/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/src/modules/actions/security.rs
  src/vsmtp/vsmtp-rule-engine/src/tests/actions.rs
  src/vsmtp/vsmtp-server/Cargo.toml
  src/vsmtp/vsmtp-server/benches/iai/receiver.rs
  src/vsmtp/vsmtp-server/benches/receiver.rs
  src/vsmtp/vsmtp-server/benches/receiver2.rs
  src/vsmtp/vsmtp-server/src/delivery/deferred.rs
  src/vsmtp/vsmtp-server/src/delivery/deliver.rs
  src/vsmtp/vsmtp-server/src/delivery/mod.rs
  src/vsmtp/vsmtp-server/src/lib.rs
  src/vsmtp/vsmtp-server/src/processing/mod.rs
  src/vsmtp/vsmtp-server/src/receiver/auth_exchange.rs
  src/vsmtp/vsmtp-server/src/receiver/connection.rs
  src/vsmtp/vsmtp-server/src/receiver/io.rs
  src/vsmtp/vsmtp-server/src/receiver/mod.rs
  src/vsmtp/vsmtp-server/src/receiver/on_mail.rs
  src/vsmtp/vsmtp-server/src/receiver/transaction.rs
  src/vsmtp/vsmtp-server/src/runtime.rs
  src/vsmtp/vsmtp-server/src/server.rs
  src/vsmtp/vsmtp-server/src/tests/auth_ignored_test.rs
  src/vsmtp/vsmtp-test/src/receiver.rs
  src/vsmtp/vsmtp-test/src/tests/auth/all_mechanism.rs
  src/vsmtp/vsmtp-test/src/tests/auth/basic.rs
  src/vsmtp/vsmtp-test/src/tests/clair.rs
  src/vsmtp/vsmtp-test/src/tests/examples/doe_family.rs
  src/vsmtp/vsmtp-test/src/tests/rset.rs
  src/vsmtp/vsmtp-test/src/tests/rules/codes/mod.rs
  src/vsmtp/vsmtp-test/src/tests/rules/quarantine/mod.rs
  src/vsmtp/vsmtp-test/src/tests/tls/cipher_suite.rs
  src/vsmtp/vsmtp-test/src/tests/tls/mod.rs
  src/vsmtp/vsmtp-test/src/tests/tls/starttls.rs
  src/vsmtp/vsmtp-test/src/tests/tls/tunneled.rs
  src/vsmtp/vsmtp-test/src/tests/tls/tunneled_with_auth.rs
  src/vsmtp/vsmtp-test/src/tests/utf8.rs
Labels: C-enhancement, P-medium

#344 Quarantine folder chown
  examples/vsl/actions/dump.vsl
  src/vsmtp/vsmtp-config/src/lib.rs
  src/vsmtp/vsmtp-config/src/tests/mod.rs
  src/vsmtp/vsmtp-server/src/receiver/on_mail.rs
Labels: C-enhancement

#346 Fix no submission listener
  Cargo.lock
  src/vsmtp/vsmtp-common/src/mail_context.rs
  src/vsmtp/vsmtp-config/src/config.rs
  src/vsmtp/vsmtp-rule-engine/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/src/dsl/action/parsing.rs
  src/vsmtp/vsmtp-rule-engine/src/dsl/object/parsing.rs
  src/vsmtp/vsmtp-rule-engine/src/dsl/rule/parsing.rs
  src/vsmtp/vsmtp-rule-engine/src/error.rs
  src/vsmtp/vsmtp-rule-engine/src/lib.rs
  src/vsmtp/vsmtp-rule-engine/src/modules/mail_context.rs
  src/vsmtp/vsmtp-rule-engine/src/tests/email/main.vsl
  src/vsmtp/vsmtp-server/src/receiver/transaction.rs
  src/vsmtp/vsmtp-server/src/server.rs
Labels: C-enhancement, A-rule-engine, P-medium, A-config

#349 Lint release + deb
  .github/workflows/post-release.yaml
  .github/workflows/pre-release.yaml
  Cargo.lock
  fuzz/Cargo.toml
  src/vsmtp/vsmtp-common/Cargo.toml
Labels: C-enhancement, P-medium, A-ci

#350 Auth Anonymous
  src/vsmtp/vsmtp-common/src/event.rs
  src/vsmtp/vsmtp-common/src/mail_context.rs
  src/vsmtp/vsmtp-common/src/mechanism.rs
  src/vsmtp/vsmtp-config/src/default.rs
  src/vsmtp/vsmtp-rule-engine/src/modules/mail_context.rs
  src/vsmtp/vsmtp-server/src/auth.rs
  src/vsmtp/vsmtp-server/src/receiver/auth_exchange.rs
  src/vsmtp/vsmtp-server/src/receiver/mod.rs
  src/vsmtp/vsmtp-test/src/tests/auth.vsl
  src/vsmtp/vsmtp-test/src/tests/auth/all_mechanism.rs
  src/vsmtp/vsmtp-test/src/tests/auth/basic.rs
  src/vsmtp/vsmtp-test/src/tests/auth/mod.rs
Labels: P-low, A-protocol, A-security

#347 Parse only when editing message
  src/vsmtp/vsmtp-common/src/event.rs
  src/vsmtp/vsmtp-common/src/mail_context.rs
  src/vsmtp/vsmtp-common/src/mechanism.rs
  src/vsmtp/vsmtp-common/src/queue.rs
  src/vsmtp/vsmtp-common/src/status.rs
  src/vsmtp/vsmtp-common/src/trait/mail_parser.rs
  src/vsmtp/vsmtp-common/src/type/reply_code.rs
  src/vsmtp/vsmtp-delivery/src/lib.rs
  src/vsmtp/vsmtp-delivery/src/transport/maildir.rs
  src/vsmtp/vsmtp-rule-engine/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/src/error.rs
  src/vsmtp/vsmtp-rule-engine/src/lib.rs
  src/vsmtp/vsmtp-rule-engine/src/modules/actions.rs
  src/vsmtp/vsmtp-rule-engine/src/modules/actions/bcc.rs
  src/vsmtp/vsmtp-rule-engine/src/modules/actions/headers.rs
  src/vsmtp/vsmtp-rule-engine/src/modules/actions/logging.rs
  src/vsmtp/vsmtp-rule-engine/src/modules/actions/rule_state.rs
  src/vsmtp/vsmtp-rule-engine/src/modules/actions/security.rs
  src/vsmtp/vsmtp-rule-engine/src/modules/actions/services.rs
  src/vsmtp/vsmtp-rule-engine/src/modules/actions/transports.rs
  src/vsmtp/vsmtp-rule-engine/src/modules/actions/utils.rs
  src/vsmtp/vsmtp-rule-engine/src/modules/actions/write.rs
  src/vsmtp/vsmtp-rule-engine/src/modules/mail_context.rs
  src/vsmtp/vsmtp-rule-engine/src/modules/message.rs
  src/vsmtp/vsmtp-rule-engine/src/modules/mod.rs
  src/vsmtp/vsmtp-rule-engine/src/rule_state.rs
  src/vsmtp/vsmtp-rule-engine/src/tests/email/main.vsl
  src/vsmtp/vsmtp-rule-engine/src/tests/email/mod.rs
  src/vsmtp/vsmtp-server/src/receiver/io.rs
Labels: C-documentation, C-enhancement, A-rule-engine, P-medium, A-vsl

#363 ci: add check doc + forbid/deny unsafe code
  .github/workflows/ci.yaml
  Cargo.lock
  SECURITY.md
  benchmarks/stress/Cargo.lock
  benchmarks/stress/Cargo.toml
  src/vqueue/src/lib.rs
  src/vsmtp/src/lib.rs
  src/vsmtp/vsmtp-common/src/lib.rs
  src/vsmtp/vsmtp-common/src/libc_abstraction.rs
  src/vsmtp/vsmtp-common/src/type/address.rs
  src/vsmtp/vsmtp-config/src/lib.rs
  src/vsmtp/vsmtp-delivery/src/lib.rs
  src/vsmtp/vsmtp-mail-parser/src/lib.rs
  src/vsmtp/vsmtp-rule-engine/src/lib.rs
  src/vsmtp/vsmtp-server/src/auth.rs
  src/vsmtp/vsmtp-server/src/lib.rs
Labels: C-enhancement, P-medium, A-security, A-ci

#364 Handle signals
  .vscode/settings.json
  Cargo.lock
  src/vsmtp/vsmtp-server/Cargo.toml
  src/vsmtp/vsmtp-server/src/runtime.rs
Labels: C-enhancement, P-medium

#365 Shell service -> Cmd service
  examples/config/antivirus/main.vsl
  examples/config/antivirus/service.vsl
  src/vsmtp/vsmtp-rule-engine/src/dsl/service/cmd.rs
  src/vsmtp/vsmtp-rule-engine/src/dsl/service/mod.rs
  src/vsmtp/vsmtp-rule-engine/src/dsl/service/parsing.rs
  src/vsmtp/vsmtp-rule-engine/src/modules/actions/services.rs
  src/vsmtp/vsmtp-rule-engine/src/modules/types.rs
  src/vsmtp/vsmtp-rule-engine/src/tests/types/service/main.vsl
  src/vsmtp/vsmtp-rule-engine/src/tests/types/service/services.vsl
Labels: A-vsl

#367 Fix: config path for tls files
  src/vsmtp/vsmtp-config/src/builder/with.rs
  src/vsmtp/vsmtp-config/src/config.rs
  src/vsmtp/vsmtp-config/src/lib.rs
  src/vsmtp/vsmtp-config/src/parser/tls_certificate.rs
  src/vsmtp/vsmtp-config/src/parser/tls_private_key.rs
  src/vsmtp/vsmtp-config/src/rustls_helper.rs
  src/vsmtp/vsmtp-config/src/virtual_tls.rs
  src/vsmtp/vsmtp-delivery/src/lib.rs
Labels: C-enhancement, P-medium, A-config, A-security

#368 Split raw headers and body
  benchmarks/stress/vsmtp.stress.toml
  fuzz/fuzz_targets/mime_parser.rs
  src/vsmtp/vsmtp-common/src/auth/credentials.rs
  src/vsmtp/vsmtp-common/src/auth/mechanism.rs
  src/vsmtp/vsmtp-common/src/event.rs
  src/vsmtp/vsmtp-common/src/lib.rs
  src/vsmtp/vsmtp-common/src/mail_context.rs
  src/vsmtp/vsmtp-common/src/queue.rs
  src/vsmtp/vsmtp-common/src/state.rs
  src/vsmtp/vsmtp-common/src/tests/event.rs
  src/vsmtp/vsmtp-common/src/trait/mail_parser.rs
  src/vsmtp/vsmtp-common/src/type/code_id.rs
  src/vsmtp/vsmtp-common/src/utils.rs
  src/vsmtp/vsmtp-delivery/src/lib.rs
  src/vsmtp/vsmtp-mail-parser/src/parser.rs
  src/vsmtp/vsmtp-mail-parser/src/tests/mime_parser/allen_p__discussion_threads__1.rs
  src/vsmtp/vsmtp-mail-parser/src/tests/mime_parser/methods.rs
  src/vsmtp/vsmtp-mail-parser/src/tests/mime_parser/mime1.rs
  src/vsmtp/vsmtp-mail-parser/src/tests/mime_parser/rfc2049/a.rs
  src/vsmtp/vsmtp-mail-parser/src/tests/mime_parser/rfc5322/a_1_1.rs
  src/vsmtp/vsmtp-mail-parser/src/tests/mime_parser/rfc5322/a_1_2.rs
  src/vsmtp/vsmtp-mail-parser/src/tests/mime_parser/rfc5322/a_1_3.rs
  src/vsmtp/vsmtp-mail-parser/src/tests/mime_parser/rfc5322/a_2.rs
  src/vsmtp/vsmtp-mail-parser/src/tests/mime_parser/rfc5322/a_3.rs
  src/vsmtp/vsmtp-mail-parser/src/tests/mime_parser/rfc5322/a_4.rs
  src/vsmtp/vsmtp-mail-parser/src/tests/mime_parser/rfc5322/a_5.rs
  src/vsmtp/vsmtp-mail-parser/src/tests/mod.rs
  src/vsmtp/vsmtp-rule-engine/src/error.rs
  src/vsmtp/vsmtp-rule-engine/src/modules/mail_context.rs
  src/vsmtp/vsmtp-rule-engine/src/modules/message.rs
  src/vsmtp/vsmtp-rule-engine/src/tests/actions.rs
  src/vsmtp/vsmtp-rule-engine/src/tests/email/main.vsl
  src/vsmtp/vsmtp-rule-engine/src/tests/email/mod.rs
  src/vsmtp/vsmtp-rule-engine/src/tests/engine/mod.rs
  src/vsmtp/vsmtp-rule-engine/src/tests/rules.rs
  src/vsmtp/vsmtp-rule-engine/src/tests/types/mod.rs
  src/vsmtp/vsmtp-server/benches/iai/receiver.rs
  src/vsmtp/vsmtp-server/benches/receiver2.rs
  src/vsmtp/vsmtp-server/src/auth.rs
  src/vsmtp/vsmtp-server/src/delivery/deferred.rs
  src/vsmtp/vsmtp-server/src/delivery/deliver.rs
  src/vsmtp/vsmtp-server/src/delivery/mod.rs
  src/vsmtp/vsmtp-server/src/lib.rs
  src/vsmtp/vsmtp-server/src/processing/mod.rs
  src/vsmtp/vsmtp-server/src/receiver/mod.rs
  src/vsmtp/vsmtp-test/src/tests/clair.rs
  src/vsmtp/vsmtp-test/src/tests/rset.rs
  src/vsmtp/vsmtp-test/src/tests/rules/quarantine/mod.rs
  src/vsmtp/vsmtp-test/src/tests/utf8.rs
Labels: P-medium, A-perf

#372 Anti relaying
  examples/vsl/anti_relaying/main.vsl
  examples/vsl/anti_relaying/net.vsl
  src/vsmtp/vsmtp-delivery/src/lib.rs
  src/vsmtp/vsmtp-rule-engine/src/api/auth.rhai
  src/vsmtp/vsmtp-rule-engine/src/modules/types.rs
  src/vsmtp/vsmtp-rule-engine/src/tests/integrations.rs
Labels: A-vsl

#374 Rcpt Behavior
  examples/config/doe_family/main.vsl
  examples/vsl/rules/rcpt.vsl
  src/vsmtp/vsmtp-rule-engine/src/api/auth.rhai
  src/vsmtp/vsmtp-rule-engine/src/error.rs
  src/vsmtp/vsmtp-rule-engine/src/modules/mail_context.rs
  src/vsmtp/vsmtp-rule-engine/src/modules/message.rs
  src/vsmtp/vsmtp-rule-engine/src/tests/email/bcc/bcc.vsl
  src/vsmtp/vsmtp-rule-engine/src/tests/email/main.vsl
Labels: C-enhancement, A-vsl

#375 Fix/doc config
  fuzz/fuzz_targets/receiver.rs
  src/vsmtp/src/lib.rs
  src/vsmtp/vsmtp-common/src/auth/mechanism.rs
  src/vsmtp/vsmtp-common/src/lib.rs
  src/vsmtp/vsmtp-common/src/libc_abstraction.rs
  src/vsmtp/vsmtp-common/src/message/mail.rs
  src/vsmtp/vsmtp-common/src/type/address.rs
  src/vsmtp/vsmtp-common/src/type/reply.rs
  src/vsmtp/vsmtp-config/src/builder/validate.rs
  src/vsmtp/vsmtp-config/src/builder/wants.rs
  src/vsmtp/vsmtp-config/src/builder/with.rs
  src/vsmtp/vsmtp-config/src/config.rs
  src/vsmtp/vsmtp-config/src/default.rs
  src/vsmtp/vsmtp-config/src/ensure.rs
  src/vsmtp/vsmtp-config/src/lib.rs
  src/vsmtp/vsmtp-config/src/parser/tls_certificate.rs
  src/vsmtp/vsmtp-config/src/parser/tls_private_key.rs
  src/vsmtp/vsmtp-config/src/rustls_helper.rs
  src/vsmtp/vsmtp-config/src/tests/root_example/secured.rs
  src/vsmtp/vsmtp-config/src/tests/root_example/tls.rs
  src/vsmtp/vsmtp-config/src/trust_dns_helper.rs
  src/vsmtp/vsmtp-config/src/virtual_tls.rs
  src/vsmtp/vsmtp-delivery/src/lib.rs
  src/vsmtp/vsmtp-delivery/src/transport/deliver.rs
  src/vsmtp/vsmtp-mail-parser/src/helpers.rs
  src/vsmtp/vsmtp-mail-parser/src/lib.rs
  src/vsmtp/vsmtp-mail-parser/src/parser.rs
  src/vsmtp/vsmtp-rule-engine/src/dsl/object/parsing.rs
  src/vsmtp/vsmtp-rule-engine/src/dsl/service/mod.rs
  src/vsmtp/vsmtp-rule-engine/src/dsl/service/smtp.rs
  src/vsmtp/vsmtp-rule-engine/src/lib.rs
  src/vsmtp/vsmtp-rule-engine/src/rule_state.rs
  src/vsmtp/vsmtp-rule-engine/src/tests/actions.rs
  src/vsmtp/vsmtp-rule-engine/src/tests/types/mod.rs
  src/vsmtp/vsmtp-server/src/delivery/mod.rs
  src/vsmtp/vsmtp-server/src/lib.rs
  src/vsmtp/vsmtp-server/src/receiver/connection.rs
  src/vsmtp/vsmtp-server/src/receiver/mod.rs
  src/vsmtp/vsmtp-server/src/receiver/transaction.rs
  src/vsmtp/vsmtp-server/src/runtime.rs
  src/vsmtp/vsmtp-server/src/server.rs
  src/vsmtp/vsmtp-test/src/lib.rs
  src/vsmtp/vsmtp-test/src/receiver.rs
  src/vsmtp/vsmtp-test/src/tests/tls/mod.rs
  src/vsmtp/vsmtp-test/src/tests/tls/starttls.rs
  src/vsmtp/vsmtp-test/src/tests/tls/tunneled.rs
Labels: C-documentation, P-medium, A-config

#379 Update examples
  examples/config/doe_family/main.vsl
  examples/config/doe_family/objects.vsl
  examples/config/doe_family/services.vsl
  examples/config/doe_family/vsmtp.toml
Labels: C-documentation

#382 fix: test deliver
  src/vsmtp/src/main.rs
  src/vsmtp/vsmtp-common/src/envelop.rs
  src/vsmtp/vsmtp-common/src/mail_context.rs
  src/vsmtp/vsmtp-common/src/message/mail.rs
  src/vsmtp/vsmtp-common/src/rcpt.rs
  src/vsmtp/vsmtp-common/src/transfer.rs
  src/vsmtp/vsmtp-delivery/Cargo.toml
  src/vsmtp/vsmtp-delivery/src/lib.rs
  src/vsmtp/vsmtp-delivery/src/transport/deliver.rs
  src/vsmtp/vsmtp-delivery/src/transport/forward.rs
  src/vsmtp/vsmtp-delivery/src/transport/maildir.rs
  src/vsmtp/vsmtp-delivery/src/transport/mbox.rs
  src/vsmtp/vsmtp-mail-parser/src/tests/mime_parser/rfc5322/a_4.rs
  src/vsmtp/vsmtp-mail-parser/src/tests/mime_parser/rfc5322/a_5.rs
  src/vsmtp/vsmtp-rule-engine/src/dsl/directives.rs
  src/vsmtp/vsmtp-rule-engine/src/dsl/service/smtp.rs
  src/vsmtp/vsmtp-server/Cargo.toml
  src/vsmtp/vsmtp-server/src/delivery/deferred.rs
  src/vsmtp/vsmtp-server/src/delivery/deliver.rs
  src/vsmtp/vsmtp-server/src/delivery/mod.rs
  src/vsmtp/vsmtp-server/src/processing/mod.rs
  src/vsmtp/vsmtp-server/src/runtime.rs
Labels: C-enhancement, P-high, A-delivery, A-queue

#388 Fix version of dependencies
  .github/workflows/post-release.yaml
  Cargo.lock
  Cargo.toml
  examples/config/antivirus.toml
  examples/config/auth.toml
  examples/config/logging.toml
  examples/config/minimal.toml
  examples/config/secured.toml
  examples/config/simple.toml
  examples/config/tls.toml
  src/vqueue/Cargo.toml
  src/vsmtp/vsmtp-config/Cargo.toml
  src/vsmtp/vsmtp-config/src/default.rs
  src/vsmtp/vsmtp-config/src/tests/root_example/antivirus.rs
  src/vsmtp/vsmtp-config/src/tests/root_example/logging.rs
  src/vsmtp/vsmtp-config/src/tests/root_example/secured.rs
  src/vsmtp/vsmtp-config/src/tests/root_example/simple.rs
  src/vsmtp/vsmtp-config/src/tests/root_example/tls.rs
  src/vsmtp/vsmtp-delivery/Cargo.toml
  src/vsmtp/vsmtp-mail-parser/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/Cargo.toml
  src/vsmtp/vsmtp-server/Cargo.toml
  src/vsmtp/vsmtp-test/Cargo.toml
Labels: P-medium, A-dependencies

#391 Unknown stage
  src/vsmtp/vsmtp-rule-engine/src/rule_engine.rs
Labels: C-enhancement, A-vsl

#392 Add `documentation` & `keywords` in Cargo.toml
  Cargo.toml
  src/vqueue/Cargo.toml
  src/vsmtp/vsmtp-common/Cargo.toml
  src/vsmtp/vsmtp-config/Cargo.toml
  src/vsmtp/vsmtp-delivery/Cargo.toml
  src/vsmtp/vsmtp-mail-parser/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/src/rule_state.rs
  src/vsmtp/vsmtp-server/Cargo.toml
  src/vsmtp/vsmtp-server/src/delivery/deliver.rs
  src/vsmtp/vsmtp-server/src/processing/mod.rs
Labels: C-documentation, P-low

#394 Fix the build of documentation for docs.rs
  .vscode/settings.json
  Cargo.toml
  src/vqueue/Cargo.toml
  src/vsmtp/vsmtp-common/Cargo.toml
  src/vsmtp/vsmtp-config/Cargo.toml
  src/vsmtp/vsmtp-config/src/config.rs
  src/vsmtp/vsmtp-config/src/default.rs
  src/vsmtp/vsmtp-delivery/Cargo.toml
  src/vsmtp/vsmtp-mail-parser/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/Cargo.toml
  src/vsmtp/vsmtp-server/Cargo.toml
  src/vsmtp/vsmtp-test/Cargo.toml
Labels: C-documentation

#405 Prepend headers
  src/vsmtp/vsmtp-common/src/mail_context.rs
  src/vsmtp/vsmtp-common/src/message/mail.rs
  src/vsmtp/vsmtp-mail-parser/src/tests/mime_parser/methods.rs
  src/vsmtp/vsmtp-rule-engine/src/api/auth.rhai
  src/vsmtp/vsmtp-rule-engine/src/api/sys-api.rhai
  src/vsmtp/vsmtp-rule-engine/src/modules/message.rs
  src/vsmtp/vsmtp-rule-engine/src/tests/email/mutate_header/main.vsl
  src/vsmtp/vsmtp-server/src/delivery/mod.rs
Labels: C-enhancement, A-vsl

#411 SPF fixes
  src/vsmtp/vsmtp-rule-engine/src/api/auth.rhai
  src/vsmtp/vsmtp-rule-engine/src/modules/actions/security.rs
Labels: C-bug, A-vsl
