Repository viridIT/vSMTP, pull requests merged in 2022-11, with the labels that each got.

#724 Improve error on vsl compilation
  src/vsmtp/vsmtp-rule-engine/src/sub_domain_hierarchy.rs
Labels: A-rule-engine

#725 Tweak/log session and more staging test
  src/vsmtp/vsmtp-server/src/server.rs
  src/vsmtp/vsmtp-test/tests/mod.rs
Labels: C-enhancement, P-medium, A-ci, A-test

#726 Transaction type refactoring
  src/vqueue/src/cli/debugger/message_show.rs
  src/vsmtp/vsmtp-common/src/mail_context.rs
  src/vsmtp/vsmtp-common/src/rcpt.rs
  src/vsmtp/vsmtp-delivery/src/transport/deliver.rs
  src/vsmtp/vsmtp-delivery/src/transport/forward.rs
  src/vsmtp/vsmtp-delivery/src/transport/maildir.rs
  src/vsmtp/vsmtp-rule-engine/src/rule_engine.rs
  src/vsmtp/vsmtp-server/src/receiver/transaction.rs
  src/vsmtp/vsmtp-test/src/config.rs
  src/vsmtp/vsmtp-test/src/tests/examples/aliases.rs
  src/vsmtp/vsmtp-test/src/tests/rule_engine/actions.rs
Labels: C-enhancement, C-refactoring

#748 Root incoming rules
  examples/alias/domain-available/fallback.vsl
  examples/alias/domain-available/incoming.vsl
  examples/alias/domain-available/main.vsl
  examples/anti_relaying/domain-available/incoming.vsl
  examples/dnsbl/conf.d/config.vsl
  examples/dnsbl/domain-available/fallback.vsl
  examples/dnsbl/domain-available/incoming.vsl
  examples/family/domain-available/fallback.vsl
  examples/family/domain-available/incoming.vsl
  examples/message/domain-available/fallback.vsl
  examples/message/domain-available/incoming.vsl
  fuzz/fuzz_targets/rules.rs
  src/vsmtp/vsmtp-rule-engine/api/default/fallback_rules.rhai
  src/vsmtp/vsmtp-rule-engine/api/default/root_incoming_rules.rhai
  src/vsmtp/vsmtp-rule-engine/src/api/dkim.rs
  src/vsmtp/vsmtp-rule-engine/src/api/logging.rs
  src/vsmtp/vsmtp-rule-engine/src/api/message.rs
  src/vsmtp/vsmtp-rule-engine/src/api/transports.rs
  src/vsmtp/vsmtp-rule-engine/src/api/utils.rs
  src/vsmtp/vsmtp-rule-engine/src/dsl/cmd/mod.rs
  src/vsmtp/vsmtp-rule-engine/src/rule_engine.rs
  src/vsmtp/vsmtp-rule-engine/src/sub_domain_hierarchy.rs
  src/vsmtp/vsmtp-rule-engine/src/tests/errors.rs
  src/vsmtp/vsmtp-rule-engine/src/tests/mod.rs
  src/vsmtp/vsmtp-server/src/delivery/deliver.rs
  src/vsmtp/vsmtp-server/src/processing/mod.rs
  src/vsmtp/vsmtp-test/src/template/auth/fallback.vsl
  src/vsmtp/vsmtp-test/src/template/auth/incoming.vsl
  src/vsmtp/vsmtp-test/src/template/ignore_vsl/incoming.vsl
  src/vsmtp/vsmtp-test/src/template/ignore_vsl/main.vsl
  src/vsmtp/vsmtp-test/src/tests/examples/aliases.rs
  src/vsmtp/vsmtp-test/src/tests/rule_engine/actions.rs
  src/vsmtp/vsmtp-test/src/tests/rule_engine/getters-auth.vsl
  src/vsmtp/vsmtp-test/src/tests/rule_engine/getters.rs
  src/vsmtp/vsmtp-test/src/tests/rule_engine/getters.vsl
  src/vsmtp/vsmtp-test/src/tests/rule_engine/rule_default/config_missing_domain_scripts/domain-available/incoming.vsl
  src/vsmtp/vsmtp-test/src/tests/rule_engine/rule_default/config_missing_fallback/conf.d/config.vsl
  src/vsmtp/vsmtp-test/src/tests/rule_engine/rule_default/config_missing_fallback/domain-available/main.vsl
  src/vsmtp/vsmtp-test/src/tests/rule_engine/rule_default/config_missing_incoming/conf.d/config.vsl
  src/vsmtp/vsmtp-test/src/tests/rule_engine/rule_default/config_missing_incoming/vsmtp.vsl
  src/vsmtp/vsmtp-test/src/tests/rule_engine/rule_default/config_missing_main/domain-available/fallback.vsl
  src/vsmtp/vsmtp-test/src/tests/rule_engine/rule_default/config_missing_main/vsmtp.vsl
  src/vsmtp/vsmtp-test/src/tests/rule_engine/rule_default/mod.rs
  src/vsmtp/vsmtp-test/src/tests/rule_engine/rule_triage/config/domain-available/fallback.vsl
  src/vsmtp/vsmtp-test/src/tests/rule_engine/rule_triage/config/domain-available/incoming.vsl
  src/vsmtp/vsmtp-test/src/tests/rule_engine/rule_triage/config/domain-available/main.vsl
  src/vsmtp/vsmtp-test/src/tests/rules/codes/custom_codes_info.vsl
  src/vsmtp/vsmtp-test/src/tests/rules/codes/custom_codes_info_pre_rcpt.vsl
  src/vsmtp/vsmtp-test/src/tests/rules/codes/mod.rs
  src/vsmtp/vsmtp-test/src/tests/rules/quarantine.rs
Labels: A-vsl, C-refactoring

#749 More test for the new `vsmtp-protocol`
  src/vsmtp/vsmtp-mail-parser/Cargo.toml
  src/vsmtp/vsmtp-mail-parser/src/traits/error.rs
  src/vsmtp/vsmtp-mail-parser/src/traits/mail_parser.rs
  src/vsmtp/vsmtp-protocol/Cargo.toml
  src/vsmtp/vsmtp-protocol/src/command.rs
  src/vsmtp/vsmtp-protocol/src/lib.rs
  src/vsmtp/vsmtp-protocol/src/receiver.rs
  src/vsmtp/vsmtp-protocol/src/receiver_handler.rs
  src/vsmtp/vsmtp-protocol/src/stream.rs
  src/vsmtp/vsmtp-server/Cargo.toml
  src/vsmtp/vsmtp-server/src/receiver/handler.rs
  src/vsmtp/vsmtp-server/src/receiver/post_transaction.rs
  src/vsmtp/vsmtp-server/src/receiver/pre_transaction.rs
  src/vsmtp/vsmtp-test/Cargo.toml
  src/vsmtp/vsmtp-test/src/receiver.rs
  src/vsmtp/vsmtp-test/src/tests/mod.rs
  src/vsmtp/vsmtp-test/src/tests/protocol/helo.rs
  src/vsmtp/vsmtp-test/src/tests/protocol/mail_from.rs
Labels: P-medium, A-test

#629 `DKIM signer` support multiple key
  Cargo.lock
  src/vsmtp/vsmtp-config/src/config.rs
  src/vsmtp/vsmtp-config/src/virtual_tls.rs
  src/vsmtp/vsmtp-rule-engine/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/README.md
  src/vsmtp/vsmtp-rule-engine/api/security.rhai
  src/vsmtp/vsmtp-rule-engine/src/api/dkim.rs
  src/vsmtp/vsmtp-rule-engine/src/api/message.rs
  src/vsmtp/vsmtp-rule-engine/src/lib.rs
  src/vsmtp/vsmtp-test/src/vsl.rs
Labels: C-documentation, A-test

#756 Update the `fuzz` target to tests the receiver of the server
  .github/workflows/staging.yaml
  fuzz/Cargo.lock
  fuzz/Cargo.toml
  fuzz/dict/command.dict
  fuzz/dict/receiver.dict
  fuzz/dict/server_config.dict
  fuzz/fuzz_targets/client.rs
  fuzz/fuzz_targets/old/mime_parser.rs
  fuzz/fuzz_targets/old/receiver.rs
  fuzz/fuzz_targets/old/rules.rs
  fuzz/fuzz_targets/old/server_config.rs
  fuzz/server/domain-available/incoming.vsl
  fuzz/server/domain-available/mydomain.com/incoming.vsl
  fuzz/server/vsmtp.vsl
Labels: A-security, A-test

#757 fix: use rolling never for log file
  src/vsmtp/vsmtp-core/src/tracing_subscriber.rs
Labels: A-log

#758 Update `TLS` / `AUTH` policy execution
  examples/anti_relaying/conf.d/config.vsl
  examples/config/complete.vsl
  examples/config/logging.vsl
  examples/config/tls.vsl
  examples/family/vsmtp.vsl
  examples/message/conf.d/config.vsl
  src/vsmtp/vsmtp-common/src/types/code_id.rs
  src/vsmtp/vsmtp-config/src/builder/with.rs
  src/vsmtp/vsmtp-config/src/config.rs
  src/vsmtp/vsmtp-config/src/default.rs
  src/vsmtp/vsmtp-config/src/tests/root_example/logging.rs
  src/vsmtp/vsmtp-config/src/tests/validate.rs
  src/vsmtp/vsmtp-config/src/virtual_tls.rs
  src/vsmtp/vsmtp-server/src/receiver/handler.rs
  src/vsmtp/vsmtp-test/src/tests/protocol/auth/basic.rs
  src/vsmtp/vsmtp-test/src/tests/protocol/auth/mod.rs
  src/vsmtp/vsmtp-test/src/tests/protocol/tls/starttls.rs
  src/vsmtp/vsmtp-test/src/tests/protocol/tls/tunneled.rs
  src/vsmtp/vsmtp-test/src/tests/protocol/tls/tunneled_with_auth.rs
Labels: P-medium, A-vsl, A-config

#688 Dmarc API upgrade
  src/vsmtp/vsmtp-rule-engine/api/security.rhai
  src/vsmtp/vsmtp-rule-engine/src/api/dmarc.rs
Labels: A-vsl

#762 ci<deps>: add dependabot for actions
  .github/dependabot.yaml
  .github/workflows/staging.yaml
Labels: A-ci, A-dependencies

#763 use rsasl v2.0.0-rc.4 + DockerHub CI
  .github/workflows/post-release.yaml
  .github/workflows/publish-docker.yaml
  .github/workflows/staging.yaml
  Cargo.lock
  docker/Dockerfile
  src/vsmtp/vsmtp-common/Cargo.toml
  src/vsmtp/vsmtp-protocol/Cargo.toml
  src/vsmtp/vsmtp-protocol/src/lib.rs
  src/vsmtp/vsmtp-protocol/src/receiver_handler.rs
  src/vsmtp/vsmtp-protocol/src/smtp_sasl.rs
  src/vsmtp/vsmtp-server/Cargo.toml
  src/vsmtp/vsmtp-server/src/receiver/handler.rs
  src/vsmtp/vsmtp-server/src/receiver/pre_transaction.rs
  src/vsmtp/vsmtp-test/Cargo.toml
Labels: A-protocol, A-dependencies

#765 CI fixes
  .github/workflows/pre-release.yaml
  release.toml
Labels: A-ci

#768 fix: update cargo-release config for 0.23.1
  release.toml
  src/vsmtp/vsmtp-common/Cargo.toml
  src/vsmtp/vsmtp-core/Cargo.toml
  src/vsmtp/vsmtp-protocol/Cargo.toml
Labels: P-medium

#779 Fix ci for release
  Cargo.lock
  release.toml
  src/vsmtp/vsmtp-core/Cargo.toml
Labels: A-ci

#780 Fix ci release + bump deps
  Cargo.lock
  release.toml
  src/vqueue/Cargo.toml
  src/vsmtp/vsmtp-core/Cargo.toml
  src/vsmtp/vsmtp-delivery/Cargo.toml
  src/vsmtp/vsmtp-mail-parser/Cargo.toml
  src/vsmtp/vsmtp-protocol/Cargo.toml
  src/vsmtp/vsmtp-server/Cargo.toml
  src/vsmtp/vsmtp-test/Cargo.toml
Labels: A-ci, A-dependencies

#782 fix: login manually (#781)
  .github/workflows/release.yml
Labels: A-ci

#783 Release v1.4.0-rc.1
  .github/workflows/release.yml
Labels: B-candidate

#784 fix: add plugins to pre-release pkg check
  .github/workflows/pre-release.yaml
  .github/workflows/staging.yaml
  Cargo.lock
  examples/antivirus/vsmtp.vsl
  examples/config/auth.vsl
  examples/config/complete.vsl
  examples/config/logging.vsl
  examples/config/minimal.vsl
  examples/config/secured.vsl
  examples/config/simple.vsl
  examples/config/tls.vsl
  src/vqueue/Cargo.toml
  src/vsmtp/plugins/vsmtp-plugin-vsl/Cargo.toml
  src/vsmtp/vsmtp-auth/Cargo.toml
  src/vsmtp/vsmtp-common/Cargo.toml
  src/vsmtp/vsmtp-config/Cargo.toml
  src/vsmtp/vsmtp-core/Cargo.toml
  src/vsmtp/vsmtp-delivery/Cargo.toml
  src/vsmtp/vsmtp-docs/Cargo.toml
  src/vsmtp/vsmtp-mail-parser/Cargo.toml
  src/vsmtp/vsmtp-protocol/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/Cargo.toml
  src/vsmtp/vsmtp-server/Cargo.toml
Labels: A-ci

#789 Release v1.4.0-rc.2
  .github/workflows/pre-release.yaml
  .github/workflows/staging.yaml
  Cargo.lock
  examples/antivirus/vsmtp.vsl
  examples/config/auth.vsl
  examples/config/complete.vsl
  examples/config/logging.vsl
  examples/config/minimal.vsl
  examples/config/secured.vsl
  examples/config/simple.vsl
  examples/config/tls.vsl
  src/vqueue/Cargo.toml
  src/vsmtp/plugins/vsmtp-plugin-vsl/Cargo.toml
  src/vsmtp/vsmtp-auth/Cargo.toml
  src/vsmtp/vsmtp-common/Cargo.toml
  src/vsmtp/vsmtp-config/Cargo.toml
  src/vsmtp/vsmtp-core/Cargo.toml
  src/vsmtp/vsmtp-delivery/Cargo.toml
  src/vsmtp/vsmtp-docs/Cargo.toml
  src/vsmtp/vsmtp-mail-parser/Cargo.toml
  src/vsmtp/vsmtp-protocol/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/Cargo.toml
  src/vsmtp/vsmtp-server/Cargo.toml
Labels: B-candidate
