Repository viridIT/vSMTP, pull requests merged in 2022-10, with the labels that each got.

#641 v1.3.1
  .github/workflows/ci.yaml
  CHANGELOG.md
  Cargo.toml
  README.md
  benchmarks/stress/Cargo.toml
  src/vqueue/Cargo.toml
  src/vsmtp/vsmtp-auth/Cargo.toml
  src/vsmtp/vsmtp-common/Cargo.toml
  src/vsmtp/vsmtp-config/Cargo.toml
  src/vsmtp/vsmtp-delivery/Cargo.toml
  src/vsmtp/vsmtp-docs/Cargo.toml
  src/vsmtp/vsmtp-mail-parser/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/Cargo.toml
  src/vsmtp/vsmtp-server/Cargo.toml
  src/vsmtp/vsmtp-test/Cargo.toml
  tools/install/deb/changelog
Labels: B-patch

#648 CI add check package
  .github/workflows/pre-release.yaml
  Cargo.lock
  src/vqueue/Cargo.toml
  src/vsmtp/vsmtp-auth/Cargo.toml
  src/vsmtp/vsmtp-common/Cargo.toml
  src/vsmtp/vsmtp-config/Cargo.toml
  src/vsmtp/vsmtp-delivery/Cargo.toml
  src/vsmtp/vsmtp-mail-parser/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/Cargo.toml
  src/vsmtp/vsmtp-server/Cargo.toml
  src/vsmtp/vsmtp-test/Cargo.toml
Labels: A-ci

#649 v1.3.2
  .github/workflows/pre-release.yaml
  Cargo.lock
  src/vqueue/Cargo.toml
  src/vsmtp/vsmtp-auth/Cargo.toml
  src/vsmtp/vsmtp-common/Cargo.toml
  src/vsmtp/vsmtp-config/Cargo.toml
  src/vsmtp/vsmtp-delivery/Cargo.toml
  src/vsmtp/vsmtp-mail-parser/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/Cargo.toml
  src/vsmtp/vsmtp-server/Cargo.toml
  src/vsmtp/vsmtp-test/Cargo.toml
Labels: B-patch

#650 v1.3.2 (2)
  src/vsmtp/vsmtp-auth/Cargo.toml
Labels: B-patch

#652 bump<dep>: bump the version of vsmtp in dependencies
  Cargo.toml
  src/vqueue/Cargo.toml
  src/vsmtp/vsmtp-auth/Cargo.toml
  src/vsmtp/vsmtp-common/Cargo.toml
  src/vsmtp/vsmtp-config/Cargo.toml
  src/vsmtp/vsmtp-delivery/Cargo.toml
  src/vsmtp/vsmtp-docs/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/Cargo.toml
  src/vsmtp/vsmtp-server/Cargo.toml
Labels: A-dependencies

#651 v1.3.3
  Cargo.lock
  Cargo.toml
  src/vqueue/Cargo.toml
  src/vsmtp/vsmtp-auth/Cargo.toml
  src/vsmtp/vsmtp-common/Cargo.toml
  src/vsmtp/vsmtp-config/Cargo.toml
  src/vsmtp/vsmtp-delivery/Cargo.toml
  src/vsmtp/vsmtp-docs/Cargo.toml
  src/vsmtp/vsmtp-mail-parser/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/Cargo.toml
  src/vsmtp/vsmtp-server/Cargo.toml
Labels: B-patch

#656 Update changelogs for the plugin system
  CHANGELOG.md
  tools/install/deb/changelog
Labels: C-documentation

#657 Information on the develop & main branches.
  README.md
Labels: C-documentation

#647 vSL objects refactor
  .vscode/settings.json
  CHANGELOG.md
  examples/alias/aliases.vsl
  examples/anti_relaying/net.vsl
  examples/family/objects.vsl
  examples/message/codes.vsl
  examples/message/mail.vsl
  src/vsmtp/vsmtp-common/src/types/reply.rs
  src/vsmtp/vsmtp-rule-engine/api/codes.rhai
  src/vsmtp/vsmtp-rule-engine/api/networks.rhai
  src/vsmtp/vsmtp-rule-engine/api/security.rhai
  src/vsmtp/vsmtp-rule-engine/api/status.rhai
  src/vsmtp/vsmtp-rule-engine/api/types.rhai
  src/vsmtp/vsmtp-rule-engine/api/utils.rhai
  src/vsmtp/vsmtp-rule-engine/src/api/logging.rs
  src/vsmtp/vsmtp-rule-engine/src/api/mail_context.rs
  src/vsmtp/vsmtp-rule-engine/src/api/message.rs
  src/vsmtp/vsmtp-rule-engine/src/api/rule_state.rs
  src/vsmtp/vsmtp-rule-engine/src/api/types.rs
  src/vsmtp/vsmtp-rule-engine/src/api/utils.rs
  src/vsmtp/vsmtp-rule-engine/src/dsl/object/mod.rs
  src/vsmtp/vsmtp-rule-engine/src/dsl/object/parsing.rs
  src/vsmtp/vsmtp-rule-engine/src/dsl/objects/api.rs
  src/vsmtp/vsmtp-rule-engine/src/dsl/objects/mod.rs
  src/vsmtp/vsmtp-rule-engine/src/dsl/objects/plugin.rs
  src/vsmtp/vsmtp-rule-engine/src/dsl/service/parsing.rs
  src/vsmtp/vsmtp-rule-engine/src/error.rs
  src/vsmtp/vsmtp-rule-engine/src/lib.rs
  src/vsmtp/vsmtp-rule-engine/src/rule_engine.rs
  src/vsmtp/vsmtp-rule-engine/src/rule_state.rs
  src/vsmtp/vsmtp-rule-engine/src/tests/actions/dump.vsl
  src/vsmtp/vsmtp-rule-engine/src/tests/actions/logs.vsl
  src/vsmtp/vsmtp-rule-engine/src/tests/actions/transports.vsl
  src/vsmtp/vsmtp-rule-engine/src/tests/actions/transports_all.vsl
  src/vsmtp/vsmtp-rule-engine/src/tests/actions/utils.vsl
  src/vsmtp/vsmtp-rule-engine/src/tests/actions/write.vsl
  src/vsmtp/vsmtp-rule-engine/src/tests/context/main.vsl
  src/vsmtp/vsmtp-rule-engine/src/tests/message/bcc/main.vsl
  src/vsmtp/vsmtp-rule-engine/src/tests/message/main.vsl
  src/vsmtp/vsmtp-rule-engine/src/tests/message/mutate_header/main.vsl
  src/vsmtp/vsmtp-rule-engine/src/tests/rules/helo.vsl
  src/vsmtp/vsmtp-rule-engine/src/tests/rules/objects-parsing.vsl
  src/vsmtp/vsmtp-rule-engine/src/tests/rules/rcpt_identifiers.vsl
  src/vsmtp/vsmtp-rule-engine/src/tests/rules/users.vsl
  src/vsmtp/vsmtp-rule-engine/src/tests/types/objects/vars.vsl
  src/vsmtp/vsmtp-test/src/tests/examples/message.rs
  src/vsmtp/vsmtp-test/src/tests/rules/codes/custom_codes_accept.vsl
  src/vsmtp/vsmtp-test/src/tests/rules/codes/custom_codes_deny.vsl
  src/vsmtp/vsmtp-test/src/tests/rules/codes/custom_codes_info.vsl
  tools/install/deb/changelog
Labels: C-enhancement, A-vsl

#669 Replaced `cfg!` if statement by cfg proc macro.
  src/vsmtp/vsmtp-rule-engine/src/rule_engine.rs
  src/vsmtp/vsmtp-rule-engine/src/rule_state.rs
Labels: C-enhancement, A-rule-engine

#666 Staging tests
  .vscode/settings.json
  Cargo.lock
  src/vsmtp/vsmtp-test/Cargo.toml
  src/vsmtp/vsmtp-test/src/config.rs
  src/vsmtp/vsmtp-test/src/tests/rules/quarantine/mod.rs
  src/vsmtp/vsmtp-test/tests/mod.rs
Labels: C-enhancement, A-protocol, A-ci, A-test

#685 Toml config to Rhai
  CHANGELOG.md
  Cargo.lock
  examples/alias/vsmtp.toml
  examples/alias/vsmtp.vsl
  examples/anti_relaying/vsmtp.toml
  examples/anti_relaying/vsmtp.vsl
  examples/antivirus/conf.d/config.vsl
  examples/antivirus/vsmtp.toml
  examples/antivirus/vsmtp.vsl
  examples/config/auth.toml
  examples/config/auth.vsl
  examples/config/complete.toml
  examples/config/complete.vsl
  examples/config/logging.toml
  examples/config/logging.vsl
  examples/config/minimal.toml
  examples/config/minimal.vsl
  examples/config/secured.toml
  examples/config/secured.vsl
  examples/config/simple.toml
  examples/config/simple.vsl
  examples/config/tls.toml
  examples/config/tls.vsl
  examples/dnsbl/vsmtp.toml
  examples/dnsbl/vsmtp.vsl
  examples/family/vsmtp.toml
  examples/family/vsmtp.vsl
  examples/message/vsmtp.toml
  examples/message/vsmtp.vsl
  fuzz/Cargo.lock
  fuzz/fuzz_targets/server_config.rs
  src/vqueue/src/main.rs
  src/vsmtp/vsmtp-common/src/types/reply_code.rs
  src/vsmtp/vsmtp-config/Cargo.toml
  src/vsmtp/vsmtp-config/src/config.rs
  src/vsmtp/vsmtp-config/src/default.rs
  src/vsmtp/vsmtp-config/src/lib.rs
  src/vsmtp/vsmtp-config/src/parser/tls_cipher_suite.rs
  src/vsmtp/vsmtp-config/src/parser/tls_protocol_version.rs
  src/vsmtp/vsmtp-config/src/tests/root_example/antivirus.rs
  src/vsmtp/vsmtp-config/src/tests/root_example/logging.rs
  src/vsmtp/vsmtp-config/src/tests/root_example/secured.rs
  src/vsmtp/vsmtp-config/src/tests/root_example/simple.rs
  src/vsmtp/vsmtp-config/src/tests/root_example/tls.rs
  src/vsmtp/vsmtp-core/src/main.rs
  src/vsmtp/vsmtp-docs/src/main.rs
  src/vsmtp/vsmtp-rule-engine/src/rule_engine.rs
  src/vsmtp/vsmtp-test/src/tests/examples/aliases.rs
  src/vsmtp/vsmtp-test/src/tests/examples/anti_relaying.rs
  src/vsmtp/vsmtp-test/src/tests/examples/dnsbl.rs
  src/vsmtp/vsmtp-test/src/tests/examples/family.rs
  src/vsmtp/vsmtp-test/src/tests/examples/message.rs
  tools/install/deb/changelog
  tools/install/deb/postinst
  tools/install/deb/postrm
  tools/install/freebsd/freebsd-vsmtp.service
Labels: A-vsl, A-config

#695 Forward target port
  CHANGELOG.md
  src/vsmtp/vsmtp-delivery/src/lib.rs
  src/vsmtp/vsmtp-delivery/src/transport/deliver.rs
  src/vsmtp/vsmtp-delivery/src/transport/forward.rs
  tools/install/deb/changelog
Labels: C-bug, A-delivery, B-patch

#708 Run the fuzz CI staging PR
  .github/workflows/fuzzer.yaml
  .github/workflows/staging.yaml
  fuzz/Cargo.lock
  fuzz/fuzz_targets/receiver.rs
Labels: C-enhancement, A-security, A-ci, A-test

#699 Prepare for sender upgrade
  Cargo.lock
  src/vqueue/Cargo.toml
  src/vqueue/src/cli/debugger/message_show.rs
  src/vqueue/src/lib.rs
  src/vsmtp/vsmtp-common/Cargo.toml
  src/vsmtp/vsmtp-common/src/event.rs
  src/vsmtp/vsmtp-common/src/mail_context.rs
  src/vsmtp/vsmtp-common/src/rcpt.rs
  src/vsmtp/vsmtp-common/src/transfer.rs
  src/vsmtp/vsmtp-common/src/types/address.rs
  src/vsmtp/vsmtp-delivery/Cargo.toml
  src/vsmtp/vsmtp-delivery/src/lib.rs
  src/vsmtp/vsmtp-delivery/src/send.rs
  src/vsmtp/vsmtp-delivery/src/sender.rs
  src/vsmtp/vsmtp-delivery/src/transport/deliver.rs
  src/vsmtp/vsmtp-delivery/src/transport/forward.rs
  src/vsmtp/vsmtp-delivery/src/transport/maildir.rs
  src/vsmtp/vsmtp-delivery/src/transport/mbox.rs
  src/vsmtp/vsmtp-rule-engine/src/api/logging.rs
  src/vsmtp/vsmtp-rule-engine/src/api/mail_context.rs
  src/vsmtp/vsmtp-rule-engine/src/api/transports.rs
  src/vsmtp/vsmtp-rule-engine/src/api/types.rs
  src/vsmtp/vsmtp-server/src/delivery/deferred.rs
  src/vsmtp/vsmtp-server/src/delivery/deliver.rs
  src/vsmtp/vsmtp-server/src/delivery/mod.rs
  src/vsmtp/vsmtp-server/src/processing/mod.rs
  src/vsmtp/vsmtp-server/src/receiver/connection.rs
  src/vsmtp/vsmtp-server/src/receiver/on_mail.rs
  src/vsmtp/vsmtp-server/src/runtime.rs
  src/vsmtp/vsmtp-test/src/tests/rule_engine/actions.rs
  src/vsmtp/vsmtp-test/src/tests/rule_engine/todo/actions/transports.vsl
  src/vsmtp/vsmtp-test/src/tests/rule_engine/todo/actions/transports_all.vsl
Labels: A-delivery

#713 More doctest for vsl api
  src/vsmtp/vsmtp-rule-engine/src/api/dkim.rs
  src/vsmtp/vsmtp-rule-engine/src/api/message.rs
  src/vsmtp/vsmtp-rule-engine/src/lib.rs
  src/vsmtp/vsmtp-test/src/vsl.rs
Labels: C-documentation, A-test

#711 tweak: enhance log message send/recv tcp
  src/vsmtp/vsmtp-delivery/src/transport/maildir.rs
  src/vsmtp/vsmtp-rule-engine/src/rule_engine.rs
  src/vsmtp/vsmtp-server/src/receiver/connection.rs
  src/vsmtp/vsmtp-server/src/receiver/transaction.rs
Labels: A-log

#714 More doctest on vsl api
  Cargo.lock
  deny.toml
  src/vsmtp/plugins/vsmtp-plugin-vsl/src/objects.rs
  src/vsmtp/vsmtp-config/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/src/api/dkim.rs
  src/vsmtp/vsmtp-rule-engine/src/api/logging.rs
  src/vsmtp/vsmtp-rule-engine/src/api/message.rs
  src/vsmtp/vsmtp-rule-engine/src/api/transports.rs
Labels: C-enhancement, A-vsl, A-test

#715 Set dev assertion on tracing logs
  src/vqueue/Cargo.toml
  src/vsmtp/vsmtp-auth/Cargo.toml
  src/vsmtp/vsmtp-config/Cargo.toml
  src/vsmtp/vsmtp-core/Cargo.toml
  src/vsmtp/vsmtp-delivery/Cargo.toml
  src/vsmtp/vsmtp-mail-parser/Cargo.toml
  src/vsmtp/vsmtp-mail-parser/src/implementation/mail_mime_parser.rs
  src/vsmtp/vsmtp-plugins/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/Cargo.toml
Labels: A-log

#718 More test
  Cargo.lock
  src/vsmtp/vsmtp-delivery/Cargo.toml
  src/vsmtp/vsmtp-delivery/src/transport/maildir.rs
  src/vsmtp/vsmtp-rule-engine/src/api/dkim.rs
Labels: C-documentation, A-delivery, A-net

#720 fix<log>: release level are info/warn/error
  Cargo.lock
  src/vqueue/Cargo.toml
  src/vsmtp/vsmtp-auth/Cargo.toml
  src/vsmtp/vsmtp-common/Cargo.toml
  src/vsmtp/vsmtp-config/Cargo.toml
  src/vsmtp/vsmtp-core/Cargo.toml
  src/vsmtp/vsmtp-delivery/Cargo.toml
  src/vsmtp/vsmtp-mail-parser/Cargo.toml
  src/vsmtp/vsmtp-plugins/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/src/api/dkim.rs
  src/vsmtp/vsmtp-rule-engine/src/api/utils.rs
  src/vsmtp/vsmtp-server/Cargo.toml
  src/vsmtp/vsmtp-test/src/tests/rule_engine/todo/actions/utils.vsl
Labels: A-log
