Repository viridIT/vSMTP, pull requests merged in 2023-02, with the labels that each got.

#990 Release 2.1
  .github/workflows/post-release.yaml
Labels: B-minor

#997 Expose server configuration in embedded modules.
  src/vsmtp/vsmtp-rule-engine/api/internal.rhai
  src/vsmtp/vsmtp-rule-engine/default/fallback_rules.rhai
  src/vsmtp/vsmtp-rule-engine/default/incoming_rules.rhai
  src/vsmtp/vsmtp-rule-engine/default/internal_rules.rhai
  src/vsmtp/vsmtp-rule-engine/default/outgoing_rules.rhai
  src/vsmtp/vsmtp-rule-engine/default/root_filter_rules.rhai
  src/vsmtp/vsmtp-rule-engine/src/rule_engine.rs
  src/vsmtp/vsmtp-rule-engine/src/sub_domain_hierarchy.rs
Labels: A-rule-engine, C-refactoring

#1003 Add links to the book instead of examples for vsl.
  README.md
Labels: C-documentation

#1004 Cmd + SMTP services documentation
  src/vsmtp/vsmtp-rule-engine/src/dsl/cmd/api.rs
  src/vsmtp/vsmtp-rule-engine/src/dsl/smtp/api.rs
Labels: C-documentation

#1008 Update `dkim::sign()` parameters
  src/vsmtp/vsmtp-rule-engine/src/api/dkim.rs
Labels: C-enhancement, P-medium, A-vsl

#1005 Allow TLS connection when no SNI is provided
  src/plugins/vsmtp-plugin-memcached/Cargo.toml
  src/vsmtp/vsmtp-config/src/builder/with.rs
  src/vsmtp/vsmtp-config/src/config.rs
  src/vsmtp/vsmtp-config/src/lib.rs
  src/vsmtp/vsmtp-config/src/rustls_helper.rs
  src/vsmtp/vsmtp-protocol/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/src/rule_engine.rs
  src/vsmtp/vsmtp-rule-engine/src/sub_domain_hierarchy.rs
  src/vsmtp/vsmtp-test/Cargo.toml
  src/vsmtp/vsmtp-test/src/receiver.rs
  src/vsmtp/vsmtp-test/src/tests/protocol/tls/starttls.rs
  src/vsmtp/vsmtp-test/src/tests/protocol/tls/tunneled.rs
  src/vsmtp/vsmtp-test/src/tests/protocol/tls/tunneled_with_auth.rs
  src/vsmtp/vsmtp-test/src/tests/rule_engine/rule_default/default_virtual/domain/testserver.com/config.vsl
  src/vsmtp/vsmtp-test/src/tests/rule_engine/rule_default/default_virtual/filter.vsl
  src/vsmtp/vsmtp-test/src/tests/rule_engine/rule_default/default_virtual/vsmtp.vsl
  src/vsmtp/vsmtp-test/src/tests/rule_engine/rule_default/mod.rs
Labels: P-medium, A-vsl, A-config

#1013 Release v2.1.1
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
  fuzz/dict/command.dict
  src/plugins/vsmtp-plugin-csv/Cargo.toml
  src/plugins/vsmtp-plugin-memcached/Cargo.toml
  src/plugins/vsmtp-plugin-mysql/Cargo.toml
  src/vqueue/Cargo.toml
  src/vsmtp/vsmtp-auth/Cargo.toml
  src/vsmtp/vsmtp-common/Cargo.toml
  src/vsmtp/vsmtp-config/Cargo.toml
  src/vsmtp/vsmtp-config/src/builder/with.rs
  src/vsmtp/vsmtp-config/src/config.rs
  src/vsmtp/vsmtp-config/src/lib.rs
  src/vsmtp/vsmtp-config/src/rustls_helper.rs
  src/vsmtp/vsmtp-core/Cargo.toml
  src/vsmtp/vsmtp-delivery/Cargo.toml
  src/vsmtp/vsmtp-mail-parser/Cargo.toml
  src/vsmtp/vsmtp-plugin-vsl/Cargo.toml
  src/vsmtp/vsmtp-protocol/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/api/internal.rhai
  src/vsmtp/vsmtp-rule-engine/default/fallback_rules.rhai
  src/vsmtp/vsmtp-rule-engine/default/incoming_rules.rhai
  src/vsmtp/vsmtp-rule-engine/default/internal_rules.rhai
  src/vsmtp/vsmtp-rule-engine/default/outgoing_rules.rhai
  src/vsmtp/vsmtp-rule-engine/default/root_filter_rules.rhai
  src/vsmtp/vsmtp-rule-engine/src/api/dkim.rs
  src/vsmtp/vsmtp-rule-engine/src/dsl/cmd/api.rs
  src/vsmtp/vsmtp-rule-engine/src/dsl/smtp/api.rs
  src/vsmtp/vsmtp-rule-engine/src/rule_engine.rs
  src/vsmtp/vsmtp-rule-engine/src/sub_domain_hierarchy.rs
  src/vsmtp/vsmtp-server/Cargo.toml
  src/vsmtp/vsmtp-test/Cargo.toml
  src/vsmtp/vsmtp-test/src/receiver.rs
  src/vsmtp/vsmtp-test/src/tests/protocol/tls/starttls.rs
  src/vsmtp/vsmtp-test/src/tests/protocol/tls/tunneled.rs
  src/vsmtp/vsmtp-test/src/tests/protocol/tls/tunneled_with_auth.rs
  src/vsmtp/vsmtp-test/src/tests/rule_engine/rule_default/default_virtual/domain/testserver.com/config.vsl
  src/vsmtp/vsmtp-test/src/tests/rule_engine/rule_default/default_virtual/filter.vsl
  src/vsmtp/vsmtp-test/src/tests/rule_engine/rule_default/default_virtual/vsmtp.vsl
  src/vsmtp/vsmtp-test/src/tests/rule_engine/rule_default/mod.rs
  tools/install/deb/changelog
Labels: B-patch

#1018 Add parameters to `transport::forward`
  CHANGELOG.md
  Cargo.lock
  src/vsmtp/vsmtp-common/src/context.rs
  src/vsmtp/vsmtp-common/src/lib.rs
  src/vsmtp/vsmtp-common/src/transfer.rs
  src/vsmtp/vsmtp-common/src/types/domain.rs
  src/vsmtp/vsmtp-common/src/types/reply.rs
  src/vsmtp/vsmtp-common/src/types/reply_code.rs
  src/vsmtp/vsmtp-common/src/types/target.rs
  src/vsmtp/vsmtp-delivery/Cargo.toml
  src/vsmtp/vsmtp-delivery/src/deliver.rs
  src/vsmtp/vsmtp-delivery/src/forward.rs
  src/vsmtp/vsmtp-delivery/src/lib.rs
  src/vsmtp/vsmtp-delivery/src/send.rs
  src/vsmtp/vsmtp-delivery/src/transport/maildir.rs
  src/vsmtp/vsmtp-protocol/Cargo.toml
  src/vsmtp/vsmtp-protocol/src/connection_kind.rs
  src/vsmtp/vsmtp-rule-engine/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/src/api/transports.rs
  src/vsmtp/vsmtp-rule-engine/src/domain_hierarchy/builder.rs
  src/vsmtp/vsmtp-rule-engine/src/domain_hierarchy/tree.rs
  src/vsmtp/vsmtp-rule-engine/src/dsl/cmd/mod.rs
  src/vsmtp/vsmtp-rule-engine/src/lib.rs
  src/vsmtp/vsmtp-rule-engine/src/rule_engine.rs
  src/vsmtp/vsmtp-rule-engine/src/sub_domain_hierarchy.rs
  src/vsmtp/vsmtp-rule-engine/src/tests/errors.rs
  src/vsmtp/vsmtp-rule-engine/src/tests/mod.rs
  src/vsmtp/vsmtp-server/src/delivery/deferred.rs
  src/vsmtp/vsmtp-server/src/delivery/deliver.rs
  src/vsmtp/vsmtp-server/src/processing/mod.rs
  src/vsmtp/vsmtp-test/Cargo.toml
  src/vsmtp/vsmtp-test/src/receiver.rs
  src/vsmtp/vsmtp-test/src/vsl.rs
  tools/install/deb/changelog
Labels: C-enhancement, A-delivery, A-vsl, C-refactoring

#1024 fix(rule-engine): action expects a dynamic that they drop immediately
  CHANGELOG.md
  src/vsmtp/vsmtp-rule-engine/src/dsl/directives/mod.rs
  tools/install/deb/changelog
Labels: C-bug, A-rule-engine

#1027 Spf context refactoring
  CHANGELOG.md
  src/vqueue/src/cli/debugger/message_show.rs
  src/vsmtp/vsmtp-common/src/context.rs
  src/vsmtp/vsmtp-rule-engine/src/api/spf.rs
  src/vsmtp/vsmtp-rule-engine/src/error.rs
  src/vsmtp/vsmtp-test/src/config.rs
  tools/install/deb/changelog
Labels: A-security, C-refactoring

#1031 Tweak `protocol` & `delivery`
  src/vsmtp/vsmtp-delivery/src/forward.rs
  src/vsmtp/vsmtp-delivery/src/send.rs
  src/vsmtp/vsmtp-protocol/src/lib.rs
  src/vsmtp/vsmtp-protocol/src/reader.rs
  src/vsmtp/vsmtp-protocol/src/receiver.rs
  src/vsmtp/vsmtp-protocol/src/smtp_sasl.rs
  src/vsmtp/vsmtp-protocol/src/writer.rs
Labels: P-medium

#928 LDAP support
  .github/workflows/plugins.yml
  .github/workflows/pre-release.yaml
  .vscode/settings.json
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  src/plugins/vsmtp-plugin-ldap/Cargo.toml
  src/plugins/vsmtp-plugin-ldap/README.md
  src/plugins/vsmtp-plugin-ldap/build.rs
  src/plugins/vsmtp-plugin-ldap/docker/README.md
  src/plugins/vsmtp-plugin-ldap/docker/certs/openldap.csr
  src/plugins/vsmtp-plugin-ldap/docker/certs/openldap.key
  src/plugins/vsmtp-plugin-ldap/docker/certs/openldap.pem
  src/plugins/vsmtp-plugin-ldap/docker/certs/openldapCA.key
  src/plugins/vsmtp-plugin-ldap/docker/certs/openldapCA.pem
  src/plugins/vsmtp-plugin-ldap/docker/docker-compose.yml
  src/plugins/vsmtp-plugin-ldap/docker/ldap-config/person.ldif
  src/plugins/vsmtp-plugin-ldap/docker/tests/simple/test.eml
  src/plugins/vsmtp-plugin-ldap/docker/tests/simple/test.sh
  src/plugins/vsmtp-plugin-ldap/docker/vsmtp-config/conf.d/config.vsl
  src/plugins/vsmtp-plugin-ldap/docker/vsmtp-config/filter.vsl
  src/plugins/vsmtp-plugin-ldap/docker/vsmtp-config/services/ad.vsl
  src/plugins/vsmtp-plugin-ldap/docker/vsmtp-config/vsmtp.vsl
  src/plugins/vsmtp-plugin-ldap/src/api.rs
  src/plugins/vsmtp-plugin-ldap/src/lib.rs
  tools/install/deb/changelog
Labels: C-enhancement, A-vsl
