Repository viridIT/vSMTP, pull requests merged in 2023-01, with the labels that each got.

#879 Fix release commit message
  CHANGELOG.md
  src/vsmtp/vsmtp-core/Cargo.toml
Labels: A-ci

#881 Release next candidate (rc.9)
  CHANGELOG.md
  src/vsmtp/vsmtp-core/Cargo.toml
Labels: B-candidate

#886 Fix bad parameters in fs module function
  src/vsmtp/vsmtp-rule-engine/src/api/fs.rs
Labels: C-bug

#891 fix: set plugin as deps for release order
  src/plugins/vsmtp-plugin-csv/Cargo.toml
  src/plugins/vsmtp-plugin-mysql/Cargo.toml
Labels: A-ci

#892 Staging next candidate (rc.11)
  src/plugins/vsmtp-plugin-csv/Cargo.toml
  src/plugins/vsmtp-plugin-mysql/Cargo.toml
Labels: B-candidate

#893 Release v1.4.0-rc.11
  src/plugins/vsmtp-plugin-csv/Cargo.toml
  src/plugins/vsmtp-plugin-mysql/Cargo.toml
Labels: B-candidate

#895 Staging latest changes (rc.12)
  .github/workflows/ci.yaml
  .github/workflows/pre-release.yaml
  .github/workflows/release.yaml
  .github/workflows/staging.yaml
  fuzz/dict/command.dict
  src/plugins/vsmtp-plugin-csv/Cargo.toml
  src/plugins/vsmtp-plugin-mysql/Cargo.toml
Labels: B-candidate

#896 Release v1.4.0-rc.12
  .github/workflows/ci.yaml
  .github/workflows/pre-release.yaml
  .github/workflows/release.yaml
  .github/workflows/staging.yaml
  fuzz/dict/command.dict
  src/plugins/vsmtp-plugin-csv/Cargo.toml
  src/plugins/vsmtp-plugin-mysql/Cargo.toml
Labels: B-candidate

#901 Prevent default user checking
  examples/config/simple.vsl
  src/vsmtp/vsmtp-config/src/default.rs
  src/vsmtp/vsmtp-config/src/lib.rs
Labels: C-bug

#902 Staging next candidate
  docker/Dockerfile
  examples/config/simple.vsl
  src/vsmtp/vsmtp-config/src/default.rs
  src/vsmtp/vsmtp-config/src/lib.rs
Labels: B-candidate

#904 Release next candidate
  docker/Dockerfile
  examples/config/simple.vsl
  src/vsmtp/vsmtp-config/src/default.rs
  src/vsmtp/vsmtp-config/src/lib.rs
Labels: B-candidate

#905 Benchmarks
  Cargo.lock
  README.md
  benchmarks/README.md
  benchmarks/hold/README.md
  benchmarks/hold/postfix/main.cf
  benchmarks/hold/vsmtp/conf.d/config.vsl
  benchmarks/hold/vsmtp/filter.vsl
  benchmarks/hold/vsmtp/vsmtp.vsl
  benchmarks/stress/README.md
  benchmarks/stress/config/conf.d/config.vsl
  benchmarks/stress/config/filter.vsl
  benchmarks/stress/config/vsmtp.vsl
  src/vsmtp/vsmtp-rule-engine/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/src/api/fs.rs
  src/vsmtp/vsmtp-rule-engine/src/api/logging.rs
Labels: C-documentation, A-vsl

#907 Fix docker image & test action
  .github/workflows/post-release.yaml
  .github/workflows/pre-release.yaml
  .github/workflows/release.yaml
  docker/Dockerfile
Labels: A-ci

#909 Update action `actions-rs/toolchain@v1` for `dtolnay/rust-toolchain@v1`
  .github/workflows/benchmark.yaml
  .github/workflows/ci.yaml
  .github/workflows/post-release.yaml
  .github/workflows/pre-release.yaml
  .github/workflows/release.yaml
  .github/workflows/staging.yaml
Labels: A-ci

#908 Staging next version
  .github/workflows/benchmark.yaml
  .github/workflows/ci.yaml
  .github/workflows/post-release.yaml
  .github/workflows/pre-release.yaml
  .github/workflows/release.yaml
  .github/workflows/staging.yaml
  Cargo.lock
  README.md
  benchmarks/README.md
  benchmarks/hold/README.md
  benchmarks/hold/postfix/main.cf
  benchmarks/hold/vsmtp/conf.d/config.vsl
  benchmarks/hold/vsmtp/filter.vsl
  benchmarks/hold/vsmtp/vsmtp.vsl
  benchmarks/stress/README.md
  benchmarks/stress/config/conf.d/config.vsl
  benchmarks/stress/config/filter.vsl
  benchmarks/stress/config/vsmtp.vsl
  docker/Dockerfile
  src/vqueue/Cargo.toml
  src/vsmtp/vsmtp-common/Cargo.toml
  src/vsmtp/vsmtp-delivery/Cargo.toml
  src/vsmtp/vsmtp-mail-parser/Cargo.toml
  src/vsmtp/vsmtp-protocol/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/src/api/fs.rs
  src/vsmtp/vsmtp-rule-engine/src/api/logging.rs
  src/vsmtp/vsmtp-server/Cargo.toml
  src/vsmtp/vsmtp-test/Cargo.toml
Labels: B-candidate

#911 Release next candidate
  .github/workflows/benchmark.yaml
  .github/workflows/ci.yaml
  .github/workflows/post-release.yaml
  .github/workflows/pre-release.yaml
  .github/workflows/release.yaml
  .github/workflows/staging.yaml
  Cargo.lock
  README.md
  benchmarks/README.md
  benchmarks/hold/README.md
  benchmarks/hold/postfix/main.cf
  benchmarks/hold/vsmtp/conf.d/config.vsl
  benchmarks/hold/vsmtp/filter.vsl
  benchmarks/hold/vsmtp/vsmtp.vsl
  benchmarks/stress/README.md
  benchmarks/stress/config/conf.d/config.vsl
  benchmarks/stress/config/filter.vsl
  benchmarks/stress/config/vsmtp.vsl
  docker/Dockerfile
  src/vqueue/Cargo.toml
  src/vsmtp/vsmtp-common/Cargo.toml
  src/vsmtp/vsmtp-delivery/Cargo.toml
  src/vsmtp/vsmtp-mail-parser/Cargo.toml
  src/vsmtp/vsmtp-protocol/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/src/api/fs.rs
  src/vsmtp/vsmtp-rule-engine/src/api/logging.rs
  src/vsmtp/vsmtp-server/Cargo.toml
  src/vsmtp/vsmtp-test/Cargo.toml
Labels: B-candidate

#913 Stage the next candidate
  .github/workflows/post-release.yaml
  .github/workflows/pre-release.yaml
  CHANGELOG.md
  Cargo.lock
  src/vqueue/Cargo.toml
  src/vsmtp/vsmtp-common/Cargo.toml
  src/vsmtp/vsmtp-delivery/Cargo.toml
  src/vsmtp/vsmtp-mail-parser/Cargo.toml
  src/vsmtp/vsmtp-protocol/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/Cargo.toml
  src/vsmtp/vsmtp-server/Cargo.toml
  src/vsmtp/vsmtp-test/Cargo.toml
Labels: B-candidate

#917 Release next candidate
  .github/workflows/post-release.yaml
  .github/workflows/pre-release.yaml
  CHANGELOG.md
  Cargo.lock
  src/vqueue/Cargo.toml
  src/vsmtp/vsmtp-common/Cargo.toml
  src/vsmtp/vsmtp-delivery/Cargo.toml
  src/vsmtp/vsmtp-mail-parser/Cargo.toml
  src/vsmtp/vsmtp-protocol/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/Cargo.toml
  src/vsmtp/vsmtp-server/Cargo.toml
  src/vsmtp/vsmtp-test/Cargo.toml
Labels: B-candidate

#919 Staging the next release
  CHANGELOG.md
  README.md
  src/vsmtp/vsmtp-rule-engine/src/api/spf.rs
Labels: B-major

#920 Release vSMTP v2.0
  CHANGELOG.md
  README.md
  src/vsmtp/vsmtp-rule-engine/src/api/spf.rs
Labels: B-major

#926 Searching for the vsmtp user on error
  CHANGELOG.md
  src/vsmtp/vsmtp-config/src/lib.rs
  tools/install/deb/changelog
Labels: C-bug, A-config

#929 Clean the `Cargo.lock`
  .vscode/settings.json
  Cargo.lock
  benchmarks/stress/Cargo.toml
  src/vqueue/Cargo.toml
  src/vsmtp/plugins/vsmtp-plugin-vsl/Cargo.toml
  src/vsmtp/vsmtp-auth/Cargo.toml
  src/vsmtp/vsmtp-common/Cargo.toml
  src/vsmtp/vsmtp-config/Cargo.toml
  src/vsmtp/vsmtp-core/Cargo.toml
  src/vsmtp/vsmtp-delivery/Cargo.toml
  src/vsmtp/vsmtp-delivery/src/transport/maildir.rs
  src/vsmtp/vsmtp-mail-parser/Cargo.toml
  src/vsmtp/vsmtp-protocol/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/Cargo.toml
  src/vsmtp/vsmtp-server/Cargo.toml
  src/vsmtp/vsmtp-test/Cargo.toml
Labels: A-security, A-dependencies, A-perf

#940 Ran `cargo update` in fuzz crate
  fuzz/Cargo.lock
Labels: A-dependencies

#959 Release 2.0.1-rc.2
  .github/workflows/post-release.yaml
  benchmarks/hold/vsmtp/vsmtp.vsl
  benchmarks/stress/config/vsmtp.vsl
  examples/alias/vsmtp.vsl
  examples/anti_relaying/vsmtp.vsl
  examples/dnsbl/vsmtp.vsl
  examples/family/vsmtp.vsl
  examples/message/vsmtp.vsl
  fuzz/server/vsmtp.vsl
  src/vsmtp/vsmtp-test/src/tests/rule_engine/rule_default/config/conf.d/config.vsl
  src/vsmtp/vsmtp-test/src/tests/rule_engine/rule_default/config/vsmtp.vsl
  src/vsmtp/vsmtp-test/src/tests/rule_engine/rule_default/config_missing_domain_scripts/conf.d/config.vsl
  src/vsmtp/vsmtp-test/src/tests/rule_engine/rule_default/config_missing_domain_scripts/vsmtp.vsl
  src/vsmtp/vsmtp-test/src/tests/rule_engine/rule_default/config_missing_incoming/conf.d/config.vsl
  src/vsmtp/vsmtp-test/src/tests/rule_engine/rule_default/config_missing_incoming/vsmtp.vsl
  src/vsmtp/vsmtp-test/src/tests/rule_engine/rule_triage/config/conf.d/config.vsl
  src/vsmtp/vsmtp-test/src/tests/rule_engine/rule_triage/config/vsmtp.vsl
Labels: B-candidate

#961 Release 2.0.1-rc.3
  tools/install/deb/vsmtp.service
Labels: B-candidate

#965 FQDN in interfaces
  CHANGELOG.md
  src/vsmtp/vsmtp-config/src/parser/socket_addr.rs
  tools/install/deb/changelog
Labels: C-enhancement, A-config

#927 `env` rhai function
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  src/plugins/vsmtp-plugin-csv/Cargo.toml
  src/vsmtp/plugins/vsmtp-plugin-vsl/src/objects.rs
  src/vsmtp/vsmtp-config/Cargo.toml
  src/vsmtp/vsmtp-config/src/lib.rs
  src/vsmtp/vsmtp-core/Cargo.toml
  src/vsmtp/vsmtp-plugin-vsl/Cargo.toml
  src/vsmtp/vsmtp-plugin-vsl/src/lib.rs
  src/vsmtp/vsmtp-plugin-vsl/src/objects.rs
  src/vsmtp/vsmtp-plugin-vsl/src/unix.rs
  src/vsmtp/vsmtp-plugin-vsl/tests/lib.rs
  src/vsmtp/vsmtp-plugin-vsl/tests/objects.rs
  src/vsmtp/vsmtp-plugin-vsl/tests/utils.rs
  src/vsmtp/vsmtp-rule-engine/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/src/api/code.rs
  src/vsmtp/vsmtp-rule-engine/src/api/dmarc.rs
  src/vsmtp/vsmtp-rule-engine/src/api/net.rs
  src/vsmtp/vsmtp-rule-engine/src/api/spf.rs
  src/vsmtp/vsmtp-rule-engine/src/api/utils.rs
  src/vsmtp/vsmtp-rule-engine/src/lib.rs
  src/vsmtp/vsmtp-rule-engine/src/rule_engine.rs
  tools/install/deb/changelog
Labels: C-enhancement, A-rule-engine, A-vsl, A-config

#968 Documentation for docker images
  CHANGELOG.md
  docker/README.md
  docker/debian/README.md
  docker/redhat/README.md
  docker/ubuntu/README.md
  tools/install/deb/changelog
Labels: C-documentation

#973 Docker setup to test plugins
  .github/workflows/plugins.yml
  src/plugins/vsmtp-plugin-mysql/docker/Dockerfile
  src/plugins/vsmtp-plugin-mysql/docker/README.md
  src/plugins/vsmtp-plugin-mysql/docker/docker-compose.yml
  src/plugins/vsmtp-plugin-mysql/docker/mysql-config/greylist-dump.sql
  src/plugins/vsmtp-plugin-mysql/docker/tests/simple/test.eml
  src/plugins/vsmtp-plugin-mysql/docker/tests/simple/test.sh
  src/plugins/vsmtp-plugin-mysql/docker/vsmtp-config/conf.d/config.vsl
  src/plugins/vsmtp-plugin-mysql/docker/vsmtp-config/filter.vsl
  src/plugins/vsmtp-plugin-mysql/docker/vsmtp-config/services/db.vsl
  src/plugins/vsmtp-plugin-mysql/docker/vsmtp-config/vsmtp.vsl
Labels: A-ci, A-test
