Repository viridIT/vSMTP, pull requests merged in 2023-03, with the labels that each got.

#1051 fix<dkim>: lowercase cmp for header last position in header hash
  Cargo.lock
  src/vsmtp/vsmtp-auth/Cargo.toml
  src/vsmtp/vsmtp-auth/src/dkim/signature.rs
  src/vsmtp/vsmtp-auth/src/dkim/tests/hash_header.rs
Labels: A-security

#1079 Refactor Rhai functions to make them easier to use
  CHANGELOG.md
  src/vsmtp/vsmtp-rule-engine/src/api/dkim.rs
  src/vsmtp/vsmtp-rule-engine/src/api/spf.rs
  tools/install/deb/changelog
Labels: C-enhancement, A-vsl, C-refactoring

#1080 Update rhai autodocs
  .vscode/settings.json
  CHANGELOG.md
  Cargo.lock
  src/plugins/vsmtp-plugin-ldap/Cargo.toml
  src/plugins/vsmtp-plugin-ldap/build.rs
  src/plugins/vsmtp-plugin-ldap/src/api.rs
  src/plugins/vsmtp-plugin-memcached/Cargo.toml
  src/plugins/vsmtp-plugin-memcached/build.rs
  src/plugins/vsmtp-plugin-memcached/src/api.rs
  src/plugins/vsmtp-plugin-mysql/Cargo.toml
  src/plugins/vsmtp-plugin-mysql/build.rs
  src/plugins/vsmtp-plugin-mysql/src/api.rs
  src/vsmtp/vsmtp-core/Cargo.toml
  src/vsmtp/vsmtp-core/build.rs
  src/vsmtp/vsmtp-plugin-vsl/src/objects.rs
  src/vsmtp/vsmtp-plugin-vsl/src/unix.rs
  src/vsmtp/vsmtp-rule-engine/src/api/auth.rs
  src/vsmtp/vsmtp-rule-engine/src/api/code.rs
  src/vsmtp/vsmtp-rule-engine/src/api/dkim.rs
  src/vsmtp/vsmtp-rule-engine/src/api/dmarc.rs
  src/vsmtp/vsmtp-rule-engine/src/api/dns.rs
  src/vsmtp/vsmtp-rule-engine/src/api/envelop.rs
  src/vsmtp/vsmtp-rule-engine/src/api/fs.rs
  src/vsmtp/vsmtp-rule-engine/src/api/logging.rs
  src/vsmtp/vsmtp-rule-engine/src/api/mail_context.rs
  src/vsmtp/vsmtp-rule-engine/src/api/message.rs
  src/vsmtp/vsmtp-rule-engine/src/api/net.rs
  src/vsmtp/vsmtp-rule-engine/src/api/spf.rs
  src/vsmtp/vsmtp-rule-engine/src/api/state.rs
  src/vsmtp/vsmtp-rule-engine/src/api/time.rs
  src/vsmtp/vsmtp-rule-engine/src/api/transports.rs
  src/vsmtp/vsmtp-rule-engine/src/api/utils.rs
  src/vsmtp/vsmtp-rule-engine/src/dsl/cmd/api.rs
  src/vsmtp/vsmtp-rule-engine/src/dsl/smtp/api.rs
  tools/install/deb/changelog
Labels: C-documentation, A-vsl

#1091 Next candidate
  Cargo.lock
  src/plugins/vsmtp-plugin-csv/Cargo.toml
  src/plugins/vsmtp-plugin-ldap/Cargo.toml
  src/plugins/vsmtp-plugin-ldap/src/api.rs
  src/plugins/vsmtp-plugin-memcached/Cargo.toml
  src/plugins/vsmtp-plugin-mysql/Cargo.toml
  src/vsmtp/vsmtp-config/Cargo.toml
  src/vsmtp/vsmtp-plugin-vsl/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/Cargo.toml
  src/vsmtp/vsmtp-rule-engine/src/domain_hierarchy/builder.rs
Labels: B-candidate

#1093 Next patch
  README.md
Labels: B-patch

#1094 Next patch
  README.md
Labels: B-patch

#1095 Staging next Minor
  README.md
Labels: B-minor

#1096 Release next Minor
  README.md
Labels: B-minor

#1085 Enhance communication `receiver <-> worker <-> deliver`
  Cargo.lock
  src/vsmtp/vsmtp-server/benches/iai/receiver.rs
  src/vsmtp/vsmtp-server/benches/receiver2.rs
  src/vsmtp/vsmtp-server/src/channel_message.rs
  src/vsmtp/vsmtp-server/src/delivery/deferred.rs
  src/vsmtp/vsmtp-server/src/delivery/deliver.rs
  src/vsmtp/vsmtp-server/src/delivery/mod.rs
  src/vsmtp/vsmtp-server/src/lib.rs
  src/vsmtp/vsmtp-server/src/processing/mod.rs
  src/vsmtp/vsmtp-server/src/receiver/handler.rs
  src/vsmtp/vsmtp-server/src/receiver/post_transaction.rs
  src/vsmtp/vsmtp-server/src/runtime.rs
  src/vsmtp/vsmtp-server/src/scheduler.rs
  src/vsmtp/vsmtp-server/src/server.rs
  src/vsmtp/vsmtp-server/src/working/mod.rs
  src/vsmtp/vsmtp-test/Cargo.toml
  src/vsmtp/vsmtp-test/src/receiver.rs
  src/vsmtp/vsmtp-test/src/tests/mod.rs
  src/vsmtp/vsmtp-test/src/tests/process/deferred.rs
  src/vsmtp/vsmtp-test/src/tests/process/delivery.rs
  src/vsmtp/vsmtp-test/src/tests/process/working.rs
  src/vsmtp/vsmtp-test/src/tests/server/mod.rs
Labels: A-delivery

#1086 Telemetry
  Cargo.lock
  src/vsmtp/vsmtp-core/Cargo.toml
  src/vsmtp/vsmtp-core/src/lib.rs
Labels: A-log

#1097 Remove the error handling for non-dev environnement
  .vscode/settings.json
  src/vsmtp/vsmtp-common/src/libc_abstraction.rs
  src/vsmtp/vsmtp-rule-engine/src/api/auth.rs
  src/vsmtp/vsmtp-rule-engine/src/api/dkim.rs
  src/vsmtp/vsmtp-rule-engine/src/api/dmarc.rs
  src/vsmtp/vsmtp-rule-engine/src/api/dns.rs
  src/vsmtp/vsmtp-rule-engine/src/api/envelop.rs
  src/vsmtp/vsmtp-rule-engine/src/api/fs.rs
  src/vsmtp/vsmtp-rule-engine/src/api/mail_context.rs
  src/vsmtp/vsmtp-rule-engine/src/api/message.rs
  src/vsmtp/vsmtp-rule-engine/src/api/spf.rs
  src/vsmtp/vsmtp-rule-engine/src/api/transports.rs
  src/vsmtp/vsmtp-rule-engine/src/dsl/directives/mod.rs
  src/vsmtp/vsmtp-rule-engine/src/error.rs
  src/vsmtp/vsmtp-rule-engine/src/lib.rs
  src/vsmtp/vsmtp-rule-engine/src/rule_engine.rs
Labels: A-rule-engine

#1126 Update the doctest for `dkim::verify()` function
  src/vsmtp/vsmtp-rule-engine/src/api/dkim.rs
Labels: A-test
